### ISSUE TITLE
multiprocessing: AssertionError: Something went wrong with the worker initialization

### ISSUE THREAD

**Issue by arianacai1997** [awslabs/gluon-ts#1004]
## Description
I tried to use the Evaluator in from "gluonts.evaluation import Evaluator", but an assertion error occurred related to multiprocessing. When I re-downloaded the tutorial in the document (https://gluon-ts.mxnet.io/examples/basic_forecasting_tutorial/tutorial.html#Create-your-own-forecast-model), the same thing happened. The code worked several weeks ago with the same OS. Besides, I changed the multiprocessing version back to the previous version, the bug still existed.

## To Reproduce

```python
from gluonts.evaluation import Evaluator
evaluator = Evaluator(quantiles=[0.1, 0.5, 0.9])
agg_metrics, item_metrics = evaluator(iter(tss), iter(forecasts), num_series=len(dataset.test))
```
## Error message or code output
(Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.)

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/caixiyan/Library/Python/3.8/lib/python/site-packages/gluonts/evaluation/_base.py", line 808, in _worker_fun
    assert isinstance(
AssertionError: Something went wrong with the worker initialization.

AssertionError                            Traceback (most recent call last)
<ipython-input-29-b25f87fe7d03> in <module>
      1 evaluator = Evaluator(quantiles=[0.1, 0.5, 0.9])
----> 2 agg_metrics, item_metrics = evaluator(iter(tss), iter(forecasts), num_series=len(dataset.test))

~/Library/Python/3.8/lib/python/site-packages/gluonts/evaluation/_base.py in __call__(self, ts_iterator, fcst_iterator, num_series)
    168                     initializer=_worker_init(self), processes=self.num_workers
    169                 )
--> 170                 rows = mp_pool.map(
    171                     func=_worker_fun,
    172                     iterable=iter(it),

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    362         in a list that is returned.
    363         '''
--> 364         return self._map_async(func, iterable, mapstar, chunksize).get()
    365 
    366     def starmap(self, func, iterable, chunksize=None):

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py in get(self, timeout)
    766             return self._value
    767         else:
--> 768             raise self._value
    769 
    770     def _set(self, i, obj):

AssertionError: Something went wrong with the worker initialization.

```
## Environment
- Operating system: MacOS 10.15.6 
- Python version: 3.8
- GluonTS version: 0.5.1
- MXNet version: 1.6.0
- multiprocessing version: 0.70.10 (also used 0.70.9)
(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
@arianacai1997 could you try on python 3.7?

**Comment by arianacai1997** [comment]
Thanks for the advice. It works!

**Comment by lostella** [comment]
let's leave this open then so that we can track python 3.8 support

**Comment by k-user** [comment]
@arianacai1997 Hey bro, What version of Python are you working on? I found the same BUG in Python3.7.4
