### ISSUE TITLE
DeepAR - Value Error when using Dynamic Features "use_feat_dynamic_real" 

### ISSUE THREAD

**Issue by sujayramaiah** [awslabs/gluon-ts#1038]
We are getting an error when trying to use the dynamic features using the `feat_dynamic_real`.

Our data is weekly and we are trying to get 19 weekly predictions.

The length of the train and test data sets are shown below.
```
Total Number of Time Series : 103
Training Data 
Length  : 359
Dyn Feat Shape : (3, 359)  # 3 Dynamic Features

Test Data:
Length  : 378
Dyn Feat Shape : (3, 378) # 3 Dynamic Features
```
Below is the code snippet: 

```
def gluonts_deepar():
    
    trainer = Trainer(
                 epochs        = 90,
                 learning_rate = 0.0019,
                 )
    
    estimator = deepar.DeepAREstimator(
                    freq                   = freq, 
                    prediction_length      = prediction_length, 
                    trainer                = trainer,
                    use_feat_dynamic_real  = True,
                    use_feat_static_cat    = True,
                    cardinality            = [103, 1]
                    ) 
       
    train_ds =  ListDataset(training_data,
                            freq=freq)   
        
    test_ds =  ListDataset(test_data,
                            freq=freq)    
    
    predictions_list = []

    # Call Estimator Fit
    predictor = estimator.train(training_data=train_ds)
    predictions = predictor.predict(test_ds)
    for prediction in predictions:
        # print (prediction)
        predictions_list.append(prediction.mean.tolist())
   
    return predictions_list
```

We are getting the following error when we are trying to iterate through the predictions.
`for prediction in predictions:`

```
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/ec2-user/SageMaker/bas-auto-ml/gluonts/gluontsutils.py", line 421, in run_gluonts_deepar
    test_data)
  File "/home/ec2-user/SageMaker/bas-auto-ml/gluonts/gluontsutils.py", line 363, in gluonts_deepar
    for prediction in predictions:
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/model/predictor.py", line 330, in predict
    num_samples=num_samples,
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/model/forecast_generator.py", line 195, in __call__
    for batch in inference_data_loader:
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/dataset/loader.py", line 108, in __iter__
    yield from self.parallel_data_loader
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/dataset/parallelized_loader.py", line 635, in same_process_iter
    itertools.islice(generator, self.batch_size)
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/dataset/parallelized_loader.py", line 243, in _sequential_sample_generator
    data_it=dataset, is_train=is_train,
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform/_base.py", line 141, in __call__
    for data_entry in data_it:
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform/_base.py", line 96, in __call__
    raise e
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform/_base.py", line 94, in __call__
    yield self.map_transform(data_entry.copy(), is_train)
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform/_base.py", line 109, in map_transform
    return self.transform(data)
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluonts/transform/convert.py", line 139, in transform
    output = np.vstack(r)
  File "<__array_function__ internals>", line 6, in vstack
  File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate

**ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 397 and the array at index 2 has size 378**

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/pandas/core/reshape/concat.py in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    279         verify_integrity=verify_integrity,
    280         copy=copy,
--> 281         sort=sort,
    282     )
    283 

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/pandas/core/reshape/concat.py in __init__(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)
    324             objs = [objs[k] for k in keys]
    325         else:
--> 326             objs = list(objs)
    327 
    328         if len(objs) == 0:

~/anaconda3/envs/mxnet_p36/lib/python3.6/concurrent/futures/process.py in _chain_from_iterable_of_lists(iterable)
    364     careful not to keep references to yielded objects.
    365     """
--> 366     for element in iterable:
    367         element.reverse()
    368         while element:

~/anaconda3/envs/mxnet_p36/lib/python3.6/concurrent/futures/_base.py in result_iterator()
    584                     # Careful not to keep a reference to the popped future
    585                     if timeout is None:
--> 586                         yield fs.pop().result()
    587                     else:
    588                         yield fs.pop().result(end_time - time.monotonic())

~/anaconda3/envs/mxnet_p36/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

~/anaconda3/envs/mxnet_p36/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 397 and the array at index 2 has size 378
```

Can you please advise if we are missing something

Thanks

**Comment by dai-ichiro** [comment]
Is this the same as below?
https://github.com/awslabs/gluon-ts/issues/280

**Comment by sujayramaiah** [comment]
Closing as duplicate.
