### ISSUE TITLE
Issue with installing GlounTS on Sagemaker notebook instance from Github

### ISSUE THREAD

**Issue by Vahidmardanlou** [awslabs/gluon-ts#1039]
## Description
I am following the instructions on https://github.com/awslabs/gluon-ts/blob/acfd7e14c4ef6eaa62fea6d6233a9e336f6366e4/examples/GluonTS_SageMaker_SDK_Tutorial.ipynb but at first step when I ran `!pip install --upgrade mxnet==1.6  git+https://github.com/awslabs/gluon-ts.git#egg=gluonts[dev]` I got the following error,

## Error message or code output
```Obtaining gluonts[dev] from git+https://github.com/awslabs/gluon-ts.git#egg=gluonts[dev]
  Updating ./src/gluonts clone
  Running command git fetch -q --tags
  Running command git reset --hard -q fc203f51f01036e854ce6a0da1a43b562074e187
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ec2-user/anaconda3/envs/mxnet_p36/bin/python /home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-_u9w80jg/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/pip/__main__.py", line 16, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/pip/_internal/cli/main.py", line 5, in <module>
      import locale
    File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/locale.py", line 16, in <module>
      import re
    File "/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/re.py", line 142, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ec2-user/anaconda3/envs/mxnet_p36/bin/python /home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-_u9w80jg/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.

```

## Environment
Note: Previously, I installed Gluon-TS (0.5.2) using `! pip install --upgrade mxnet==1.6 gluonts` and if I do `! pip list` I can see the package is installed but when I ran `!pip uninstall glounts` it says `WARNING: Skipping glounts as it is not installed.`

- Operating system: Sagemaker notebook instance with conda_mxnet_p36 kernel.
- Python version: 3.6
- GluonTS version: 0.5.2 is already installed.
- MXNet version:1.6

**Comment by jaheba** [comment]
According to [this](https://github.com/iterative/dvc/issues/1995), it could be that `enum34` is installed.

Can you check whether this is also the case here?

**Comment by Vahidmardanlou** [comment]
Thanks @jaheba ! That was the issue and by running `!pip uninstall -y enum34` it is resolved.
