### ISSUE TITLE
Sample function of MixtureDistribution class errors for (d,)-shaped distributions when num_samples>1

### ISSUE THREAD

**Issue by elenaehrlich** [awslabs/gluon-ts#1041]
## Description
I came across a bug in the MixtureDistribution class, where sampling is prohibited by an incompatible shapes broadcast (see MWEs 1 and 2 below).

## To Reproduce

MWE-1 demonstrates where sampling is prohibited by an incompatible shapes broadcast
```from gluonts.mx.distribution import MixtureDistribution, Gaussian, Gamma, Distribution
import mxnet as mx
from mxnet import nd
import numpy as np
gaussian = Gaussian(mu=nd.array([0.]), sigma=nd.array([1.]))
gamma = Gamma(alpha=nd.array([9.]), beta=nd.array([2.]))
mixture = MixtureDistribution(mixture_probs=nd.array([0.9, 0.1]), components=[gaussian, gamma])
mixture.sample(num_samples=1) # WORKS
mixture.sample(num_samples=10) # DOESN"T WORK
```

## MWE-1 Error message or code output
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-30-52d279ea9fbf>", line 9, in <module>
    mixture.sample(num_samples=10) # DOESN"T WORK
  File "/Users/eeehrlic/Documents/projects/capstone/gluon-ts/src/gluonts/mx/distribution/mixture.py", line 155, in sample
    # idx = idx.broadcast_like(samples_list[0])
  File "/usr/local/lib/python3.8/site-packages/mxnet/ndarray/ndarray.py", line 2333, in broadcast_like
    return self.broadcast_to(other.shape)
  File "/usr/local/lib/python3.8/site-packages/mxnet/ndarray/ndarray.py", line 2290, in broadcast_to
    raise ValueError(err_str)
ValueError: operands could not be broadcast together with remapped shapes[original->remapped]: (10,) and requeste
```

MWE-2 Incompatible shapes broadcast also prohibits sampling from mixture of multivariate distributions.
```import mxnet as mx
from gluonts.mx.distribution import MixtureDistribution
from gluonts.mx.distribution.multivariate_gaussian import *
mu1_bi = mx.nd.array([0., 0.])
mu2_bi = mx.nd.array([2., 2.])
sigma_bi = mx.nd.array([[0.01, 0.], [0., 0.01]])
mvgaussian1 = MultivariateGaussian(mu=mu1_bi, L=sigma_bi)
mvgaussian2 = MultivariateGaussian(mu=mu2_bi, L=sigma_bi)
p = mx.nd.array([0.6])
mix_prob_tensor = mx.nd.stack(p, 1.0 - p, axis=-1)
mixture = MixtureDistribution(mixture_probs=mix_prob_tensor, components=[mvgaussian1, mvgaussian2])
samples = mixture.sample() # DOESN'T WORK
samples = mixture.sample(1) # DOESN'T WORK
samples = mixture.sample(10) # DOESN'T WORK
```

MWE-2 Error message or code output
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-6d163038db74>", line 1, in <module>
    samples = mixture.sample() # DOESN'T WORK
  File "/Users/eeehrlic/Documents/projects/capstone/gluon-ts/src/gluonts/mx/distribution/mixture.py", line 155, in sample
    idx = idx.broadcast_like(samples_list[0])
  File "/usr/local/lib/python3.8/site-packages/mxnet/ndarray/ndarray.py", line 2333, in broadcast_like
    return self.broadcast_to(other.shape)
  File "/usr/local/lib/python3.8/site-packages/mxnet/ndarray/ndarray.py", line 2285, in broadcast_to
    raise ValueError(err_str)
ValueError: operands could not be broadcast together with remapped shapes[original->remapped]: (1, 1) and requested shape (2,)
```

## Environment
- Operating system: MacOs 10.14.6
- Python version: Python 3.8.5
- GluonTS version: 0.5.1.dev92+g14a1ec8
- MXNet version: 1.6.0

**Comment by PascalIversen** [comment]
Hey @elenaehrlich,

I think this is not a bug, but we should maybe catch this with an assertion... The `mixture_probs` have to be of shape (1,2). This will work:

```
import mxnet as mx
from mxnet import nd
import numpy as np
gaussian = Gaussian(mu=nd.array([0.]), sigma=nd.array([1.]))
gamma = Gamma(alpha=nd.array([9.]), beta=nd.array([2.]))
mixture = MixtureDistribution(mixture_probs=nd.array([0.9, 0.1]), components=[gaussian, gamma])
mixture.sample(num_samples=1) # WORKS
mixture.sample(num_samples=10) # WORKS
```

The reason is that the one dimensional batch shape is a special case of higher dimensional batch shapes:

```
gaussian = Gaussian(mu=nd.array([0., 0.1]), sigma=nd.array([1., 1.1]))
gamma = Gamma(alpha=nd.array([9., 1.]), beta=nd.array([2., 3.]))
mixture = MixtureDistribution(mixture_probs=nd.array([[0.9, 0.1], [0.1, 0.9]]), components=[gaussian, gamma])
mixture.sample(num_samples=1) # WORKS
mixture.sample(num_samples=10) # WORKS
```

**Comment by PascalIversen** [comment]
Never mind, I just saw your [PR](https://github.com/awslabs/gluon-ts/pull/1042) regarding this and I think this can be closed.
