### ISSUE TITLE
Error importing ComplexSeasonalTimeSeries on python 3.7

### ISSUE THREAD

**Issue by kuperov** [awslabs/gluon-ts#107]
Hi Gluon TS maintainers

What a great project. I found a little glitch under anaconda and windows 10, when trying to import the `ComplexSeasonalTimeSeries` class. The issue appears similar to #62, #67, and #68 but those issues show as fixed, and this error occurs on HEAD.

To reproduce, create a new anaconda environment for python 3.7, clone the repo and install from source. Then:
```
C:\path>python
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from gluonts.dataset.artificial._base import ComplexSeasonalTimeSeries
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\alex\src\gluon-ts\src\gluonts\dataset\artificial\__init__.py", line 2, in <module>
    from ._base import (
  File "c:\users\alex\src\gluon-ts\src\gluonts\dataset\artificial\_base.py", line 20, in <module>
    from gluonts.dataset.artificial.recipe import (
  File "c:\users\alex\src\gluon-ts\src\gluonts\dataset\artificial\recipe.py", line 242, in <module>
    class LinearTrend(Lifted):
  File "c:\users\alex\src\gluon-ts\src\gluonts\dataset\artificial\recipe.py", line 244, in LinearTrend
    def __init__(self, slope_fun: Callable = Constant(1.0)) -> None:
  File "c:\users\alex\src\gluon-ts\src\gluonts\core\component.py", line 352, in validator
    **init_fields,
  File "C:\Users\Alex\.conda\envs\gts\lib\site-packages\pydantic\main.py", line 410, in create_model
    config=config,
  File "C:\Users\Alex\.conda\envs\gts\lib\site-packages\pydantic\fields.py", line 107, in infer
    schema=schema,
  File "C:\Users\Alex\.conda\envs\gts\lib\site-packages\pydantic\fields.py", line 87, in __init__
    self.prepare()
  File "C:\Users\Alex\.conda\envs\gts\lib\site-packages\pydantic\fields.py", line 135, in prepare
    self._populate_sub_fields()
  File "C:\Users\Alex\.conda\envs\gts\lib\site-packages\pydantic\fields.py", line 240, in _populate_sub_fields
    assert issubclass(origin, Mapping)
AssertionError
>>>
```

But in contrast, repeating the above with python 3.6, we get
```
C:\path>python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from gluonts.dataset.artificial._base import ComplexSeasonalTimeSeries
>>>
```

Cheers
Alex

**Comment by jaheba** [comment]
Thanks Alex!

This error does not seem limited to windows: I'm also getting the same error on my OS X machine with Python 3.7

**Comment by jaheba** [comment]
From what I understand, updating the pydantic version fixes the issue. However, that requires some changes in the code base first.

**Comment by kuperov** [comment]
Thanks guys!
