### ISSUE TITLE
Cannot predict using NegativeBinominalOutput

### ISSUE THREAD

**Issue by Ishitori** [awslabs/gluon-ts#150]
## Description
I am training example model with NegativeBinominalOutput. After fixing #91 it trains well, but I cannot make a prediction. The Minimal reproducible example is attached. It is the same as in #91, but just have a prediction code.

## To Reproduce
```
import pandas as pd
from gluonts.dataset.common import ListDataset

url = "https://raw.githubusercontent.com/numenta/NAB/master/data/realTweets/Twitter_volume_AMZN.csv"
df = pd.read_csv(url, header=0, index_col=0)

training_data = ListDataset(
    [{"start": df.index[0], "target": df.value[:"2015-04-05 00:00:00"]}],
    freq="5min"
)
from gluonts.model.deepar import DeepAREstimator
from gluonts.trainer import Trainer
from gluonts.distribution import NegativeBinomialOutput

estimator = DeepAREstimator(freq="5min", prediction_length=12,
                            distr_output=NegativeBinomialOutput(),
                            trainer=Trainer(epochs=1))
predictor = estimator.train(training_data=training_data)

for forecast in predictor.predict(training_data):
    print(forecast.mean)

```

## Error Message
```
Traceback (most recent call last):
  File "/home/ubuntu/projects/mwe_neg_binominal_predict.py", line 19, in <module>
    for forecast in predictor.predict(training_data):
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/gluonts/model/predictor.py", line 277, in predict
    outputs = self.prediction_net(*inputs).asnumpy()
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/mxnet/gluon/block.py", line 548, in __call__
    out = self.forward(*args)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/mxnet/gluon/block.py", line 925, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/gluonts/model/deepar/_network.py", line 526, in hybrid_forward
    begin_states=state,
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/gluonts/model/deepar/_network.py", line 463, in sampling_decoder
    new_samples = distr.sample()
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/gluonts/distribution/neg_binomial.py", line 92, in sample
    s, mu=self.mu, alpha=self.alpha, num_samples=num_samples
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/gluonts/distribution/distribution.py", line 241, in _sample_multiple
    samples = sample_func(*args_expanded, **kwargs_expanded)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/gluonts/distribution/neg_binomial.py", line 88, in s
    x = F.minimum(F.random.gamma(r, theta), 1e6)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/mxnet/ndarray/random.py", line 383, in gamma
    [alpha, beta], shape, dtype, ctx, out, kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/mxnet/ndarray/random.py", line 38, in _random_helper
    return sampler(*params, shape=shape, dtype=dtype, out=out, **kwargs)
  File "<string>", line 68, in _sample_gamma
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/mxnet/_ctypes/ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/mxnet/base.py", line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: vector::_M_range_insert
```

## Environment
- Operating system: Ubuntu
- Python version: 3.7
- GluonTS version: 0.4 (--pre installation)

**Comment by Ishitori** [comment]
It was something weird with my MXNet installation. Once I reinstalled MXNet this bug went away.
