### ISSUE TITLE
COV19-forecast.ipynb in examples: Evaluator has bugs

### ISSUE THREAD

**Issue by winnieshen96** [awslabs/gluon-ts#1570]
## Description
When I tried to run COV19-forecast.ipynb, going down to the Evaluation part, the CustomEvaluator gives me a PicklingError; and when I changed the code to Evaluator as taught in the tutorial, it gives me a AttributeError. I have attached the link to both below. 

I strictly followed either the example in the github repo and in the tutorial, did not changed anything except adding "mx" to some of the library imports (eg. from gluonts.mx.trainer import Trainer).

# 1st bug on Evaluator 

## To Reproduce
Link to the example notebook is [here](https://github.com/awslabs/gluon-ts/blob/master/examples/COV19-forecast.ipynb)
The original code writes its own CustomEvaluator, which gives the following bug

```python
from gluonts.evaluation import Evaluator


class CustomEvaluator(Evaluator):

    def get_metrics_per_ts(self, time_series, forecast):
        successive_diff = np.diff(time_series.values.reshape(len(time_series)))
        successive_diff = successive_diff ** 2
        successive_diff = successive_diff[:-prediction_length]
        denom = np.mean(successive_diff)
        pred_values = forecast.samples.mean(axis=0)
        true_values = time_series.values.reshape(len(time_series))[-prediction_length:]
        num = np.mean((pred_values - true_values) ** 2)
        rmsse = num / denom
        metrics = super().get_metrics_per_ts(time_series, forecast)
        metrics["RMSSE"] = rmsse
        return metrics

    def get_aggregate_metrics(self, metric_per_ts):
        wrmsse = metric_per_ts["RMSSE"].mean()
        agg_metric, _ = super().get_aggregate_metrics(metric_per_ts)
        agg_metric["MRMSSE"] = wrmsse
        return agg_metric, metric_per_ts


evaluator = CustomEvaluator(quantiles=[0.5, 0.67, 0.95, 0.99])
agg_metrics, item_metrics = evaluator(iter(tss), iter(forecasts), num_series=len(test_ds))
print(json.dumps(agg_metrics, indent=4))
```

## Error message or code output
PicklingError: Can't pickle <class '__main__.CustomEvaluator'>: attribute lookup CustomEvaluator on __main__ failed

```
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<command-282946603298367> in <module>
     26 evaluator = CustomEvaluator(quantiles=[0.5, 0.67, 0.95, 0.99])
     27 # evaluator = Evaluator(quantiles=[0.5, 0.67, 0.95, 0.99]) # PicklingError: Can't pickle <class '__main__.CustomEvaluator'>: attribute lookup CustomEvaluator on __main__ failed
---> 28 agg_metrics, item_metrics = evaluator(iter(tss), iter(forecasts), num_series=len(test_ds))
     29 print(json.dumps(agg_metrics, indent=4))

/local_disk0/.ephemeral_nfs/envs/pythonEnv-90c577b8-4459-4c0e-bcd7-5924751f446f/lib/python3.7/site-packages/gluonts/evaluation/_base.py in __call__(self, ts_iterator, fcst_iterator, num_series)
    219                     func=partial(worker_function, self),
    220                     iterable=iter(it),
--> 221                     chunksize=self.chunk_size,
    222                 )
    223                 mp_pool.close()

/local_disk0/.ephemeral_nfs/envs/pythonEnv-90c577b8-4459-4c0e-bcd7-5924751f446f/lib/python3.7/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    266         in a list that is returned.
    267         '''
--> 268         return self._map_async(func, iterable, mapstar, chunksize).get()
    269 
    270     def starmap(self, func, iterable, chunksize=None):

/local_disk0/.ephemeral_nfs/envs/pythonEnv-90c577b8-4459-4c0e-bcd7-5924751f446f/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

/local_disk0/.ephemeral_nfs/envs/pythonEnv-90c577b8-4459-4c0e-bcd7-5924751f446f/lib/python3.7/multiprocessing/pool.py in _handle_tasks(taskqueue, put, outqueue, pool, cache)
    429                         break
    430                     try:
--> 431                         put(task)
    432                     except Exception as e:
    433                         job, idx = task[:2]

/local_disk0/.ephemeral_nfs/envs/pythonEnv-90c577b8-4459-4c0e-bcd7-5924751f446f/lib/python3.7/multiprocessing/connection.py in send(self, obj)
    204         self._check_closed()
    205         self._check_writable()
--> 206         self._send_bytes(_ForkingPickler.dumps(obj))
    207 
    208     def recv_bytes(self, maxlength=None):

/local_disk0/.ephemeral_nfs/envs/pythonEnv-90c577b8-4459-4c0e-bcd7-5924751f446f/lib/python3.7/multiprocessing/reduction.py in dumps(cls, obj, protocol)
     49     def dumps(cls, obj, protocol=None):
     50         buf = io.BytesIO()
---> 51         cls(buf, protocol).dump(obj)
     52         return buf.getbuffer()
     53 

PicklingError: Can't pickle <class '__main__.CustomEvaluator'>: attribute lookup CustomEvaluator on __main__ failed
```

# 2nd bug on Evaluator

## To Reproduce

I removed the CustomEvaluator and followed the tutorial [here](https://ts.gluon.ai/tutorials/forecasting/extended_tutorial.html#Compute-metrics)

```python
evaluator = Evaluator(quantiles=[0.5, 0.67, 0.95, 0.99]) 
agg_metrics, item_metrics = evaluator(iter(tss), iter(forecasts), num_series=len(test_ds))
print(json.dumps(agg_metrics, indent=4))
```

## Error message or code output
AttributeError: 'Quantile' object has no attribute 'loss_name'

```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-90c577b8-4459-4c0e-bcd7-5924751f446f/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-90c577b8-4459-4c0e-bcd7-5924751f446f/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-90c577b8-4459-4c0e-bcd7-5924751f446f/lib/python3.7/site-packages/gluonts/evaluation/_base.py", line 54, in worker_function
    return evaluator.get_metrics_per_ts(ts, forecast)
  File "/local_disk0/.ephemeral_nfs/envs/pythonEnv-90c577b8-4459-4c0e-bcd7-5924751f446f/lib/python3.7/site-packages/gluonts/evaluation/_base.py", line 395, in get_metrics_per_ts
    pred_target, forecast_quantile, quantile.value
AttributeError: 'Quantile' object has no attribute 'loss_name'
"""

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
<command-282946603298367> in <module>
     26 # evaluator = CustomEvaluator(quantiles=[0.5, 0.67, 0.95, 0.99])
     27 evaluator = Evaluator(quantiles=[0.5, 0.67, 0.95, 0.99])
---> 28 agg_metrics, item_metrics = evaluator(iter(tss), iter(forecasts), num_series=len(test_ds))
     29 print(json.dumps(agg_metrics, indent=4))

/local_disk0/.ephemeral_nfs/envs/pythonEnv-90c577b8-4459-4c0e-bcd7-5924751f446f/lib/python3.7/site-packages/gluonts/evaluation/_base.py in __call__(self, ts_iterator, fcst_iterator, num_series)
    219                     func=partial(worker_function, self),
    220                     iterable=iter(it),
--> 221                     chunksize=self.chunk_size,
    222                 )
    223                 mp_pool.close()

/local_disk0/.ephemeral_nfs/envs/pythonEnv-90c577b8-4459-4c0e-bcd7-5924751f446f/lib/python3.7/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    266         in a list that is returned.
    267         '''
--> 268         return self._map_async(func, iterable, mapstar, chunksize).get()
    269 
    270     def starmap(self, func, iterable, chunksize=None):

/local_disk0/.ephemeral_nfs/envs/pythonEnv-90c577b8-4459-4c0e-bcd7-5924751f446f/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

AttributeError: 'Quantile' object has no attribute 'loss_name'
```

## Environment
- Operating system:
- Python version: 3.7.10
- GluonTS version:0.7.6
- MXNet version:1.8.0
- Databricks cluster: 7.3 LTS ML (includes Apache Spark 3.0.1, Scala 2.12)

**Comment by winnieshen96** [comment]
Seems to be a environment issue. I changed from Databricks to AzureML and used python 3.8 to install mxnet and gluonts. There, after adding "mx" to several buggy imports everything works fine.

**Comment by khuyentran1401** [comment]
> Seems to be a environment issue. I changed from Databricks to AzureML and used the default conda environment azureml_py38 to install mxnet and gluonts. There, after adding "mx" to several buggy imports everything works fine.

@winnieshen96 Where did you add mx at? I got the same error:
```bash
  File "/Users/khuyen/baysian_neural_network/baysian_neuralnet/src/baysian_neuralnet/pipelines/train/nodes.py", line 259, in evaluate
    agg_metrics, item_metrics = evaluator(
  File "/Users/khuyen/baysian_neural_network/baysian_neuralnet/venv/lib/python3.8/site-packages/gluonts/evaluation/_base.py", line 218, in __call__
    rows = mp_pool.map(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: 'Quantile' object has no attribute 'loss_name'
```
I looked at the source code of the `Quantile` object in the directory `venv/lib/python3.8/site-packages/gluonts/model/forecast.py` and there is clearly attribute `loss_name`:
```python
class Quantile(NamedTuple):
    value: float
    name: str

    @property
    def loss_name(self):
        return f"QuantileLoss[{self.name}]"

    @property
    def weighted_loss_name(self):
        return f"wQuantileLoss[{self.name}]"

    @property
    def coverage_name(self):
        return f"Coverage[{self.name}]"
```

I'm not sure why I got this weird error. Any suggestion would be greatly appreciated.

## Environment
Operating system: macOS Big Sur version 11.4
Python version: 3.8.10
GluonTS version:0.8.0
MXNet version:1.8.0.post0
