### ISSUE TITLE
num_workers argument to Estimator.train causes CUDA initialization error

### ISSUE THREAD

**Issue by pbruneau** [awslabs/gluon-ts#1587]
## Description
Trying to set `num_workers` to a non-zero value (e.g. 4) as parameter to Estimator.train causes a CUDA initialization error (reported in the _Error message or code output_ section below). Is this related to #898 and #1054? I tried to add the block:

```
import multiprocessing
multiprocessing.set_start_method("spawn", force=True)
```

at the end of my imports (following #1054), but then I get the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/opt/conda/envs/rapids/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/opt/conda/envs/rapids/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/opt/conda/envs/rapids/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/files/postprocessing/DeepAREstimator_Sample.py", line 61, in <module>
    predictor = estimator.train(train_ds, num_workers=4)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/mx/model/estimator.py", line 207, in train
    cache_data=cache_data,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/mx/model/estimator.py", line 158, in train_model
    shuffle_buffer_length=shuffle_buffer_length,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/model/deepar/_estimator.py", line 411, in create_training_data_loader
    **kwargs,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/dataset/loader.py", line 305, in TrainDataLoader
    if num_batches_per_epoch is None
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/dataset/loader.py", line 216, in __iter__
    max_queue_size=self.num_prefetch,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/dataset/loader.py", line 54, in __init__
    self.manager = mp.Manager()
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/context.py", line 56, in Manager
    m.start()
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/managers.py", line 563, in start
    self._process.start()
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "DeepAREstimator_Sample.py", line 61, in <module>
    predictor = estimator.train(train_ds, num_workers=4)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/mx/model/estimator.py", line 207, in train
    cache_data=cache_data,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/mx/model/estimator.py", line 158, in train_model
    shuffle_buffer_length=shuffle_buffer_length,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/model/deepar/_estimator.py", line 411, in create_training_data_loader
    **kwargs,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/dataset/loader.py", line 305, in TrainDataLoader
    if num_batches_per_epoch is None
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/dataset/loader.py", line 216, in __iter__
    max_queue_size=self.num_prefetch,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/dataset/loader.py", line 54, in __init__
    self.manager = mp.Manager()
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/context.py", line 56, in Manager
    m.start()
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/managers.py", line 567, in start
    self._address = reader.recv()
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

## To Reproduce
Setting the `num_workers` parameter to 4 in the last line of the following gist: https://gist.github.com/pbruneau/1066dbf375033cfc35ea3e758b72dc32

## Error message or code output
```
Process worker_3:
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/envs/rapids/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/dataset/loader.py", line 98, in worker_fn
    stacked_batch = stack_fn(batch)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/mx/batchify.py", line 94, in batchify
    for key in data[0].keys()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/mx/batchify.py", line 94, in <dictcomp>
    for key in data[0].keys()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/mx/batchify.py", line 75, in stack
    data = mx.nd.array(data, dtype=dtype, ctx=ctx)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/mxnet/ndarray/utils.py", line 146, in array
    return _array(source_array, ctx=ctx, dtype=dtype)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/mxnet/ndarray/ndarray.py", line 3371, in array
    arr = empty(source_array.shape, ctx, dtype)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/mxnet/ndarray/ndarray.py", line 4822, in empty
    return NDArray(handle=_new_alloc_handle(shape, ctx, False, dtype))
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/mxnet/ndarray/ndarray.py", line 186, in _new_alloc_handle
    ctypes.byref(hdl)))
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/mxnet/base.py", line 246, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: Traceback (most recent call last):
  File "../src/engine/./../common/cuda_utils.h", line 379
CUDA: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading: initialization error
learning rate from ``lr_scheduler`` has been overwritten by ``learning_rate`` in optimizer.
  0%|                                                                                                           | 0/1000 [02:00<?, ?it/s]
Traceback (most recent call last):
  File "DeepAREstimator_Sample.py", line 58, in <module>
    predictor = estimator.train(train_ds, num_workers=4)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/mx/model/estimator.py", line 207, in train
    cache_data=cache_data,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/mx/model/estimator.py", line 179, in train_model
    validation_iter=validation_data_loader,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/mx/trainer/_base.py", line 379, in __call__
    num_batches_to_use=self.num_batches_per_epoch,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/gluonts/mx/trainer/_base.py", line 358, in loop
    lv,
UnboundLocalError: local variable 'lv' referenced before assignment
```

## Environment
- Operating system:
- Python version: 3.7
- GluonTS version: 0.7.6
- MXNet version: 1.8.0

**Comment by jaheba** [comment]
Hey, I think the first error message happens if you don’t put your entry point code in an `if __name__ == "__main__"` block, because it then tries to run that code in the other processes as well. Not sure if it fixes the other issue though.

**Comment by pbruneau** [comment]
Thanks @jaheba! Indeed using a `if __name__ == "__main__"` block in conjunction with the multiprocessing import block mentioned above solves the issue. I'm closing the issue then.
