### ISSUE TITLE
Multivariate time series raise an error

### ISSUE THREAD

**Issue by lostella** [awslabs/gluon-ts#160]
## Description
I'm trying to model 4-dimensional time series using `MultivariateGaussianOutput`, but training fails due to some invalid loss value.

## To Reproduce

```
import numpy as np

from gluonts.dataset.common import ListDataset
from gluonts.distribution import MultivariateGaussianOutput
from gluonts.model.deepar import DeepAREstimator
from gluonts.trainer import Trainer

train_dataset = ListDataset(
    data_iter=[
        {
            "start": "2019-01-01 00:00:00",
            "target": np.ones(shape=(4, 100)).tolist(),
        },
    ],
    freq="5min",
)

estimator = DeepAREstimator(
    'H', prediction_length=5, trainer=Trainer(epochs=3, hybridize=False),
    distr_output=MultivariateGaussianOutput(dim=4),
)

predictor = estimator.train(train_dataset)
```

## Error Message

```
Traceback (most recent call last):
  File "/Users/stellalo/gluon-ts/examples/run_multivariate.py", line 15, in <module>
    freq="5min",
  File "/Users/stellalo/gluon-ts/src/gluonts/dataset/common.py", line 259, in __init__
    self.list_data = [process(data) for data in data_iter]
  File "/Users/stellalo/gluon-ts/src/gluonts/dataset/common.py", line 259, in <listcomp>
    self.list_data = [process(data) for data in data_iter]
  File "/Users/stellalo/gluon-ts/src/gluonts/dataset/common.py", line 435, in __call__
    data = t(data)
  File "/Users/stellalo/gluon-ts/src/gluonts/dataset/common.py", line 374, in __call__
    f"JSON array has bad shape - expected {self.req_ndim} "
gluonts.core.exception.GluonTSDataError: JSON array has bad shape - expected 1 dimensions, got -1
```

## Environment
- Operating system: macOS
- Python version: 3.6.6
- GluonTS version: master (35cc49bc66fcf0ebc7225916fc2d3edd58f5cb49)

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by davidlkl** [comment]
I have done some investigation based on the code above.

When L, the Lower triangular Cholesky factor of covariance matrix has negative diagonal values, the log_prob will become undefined and therefore the weighted average loss become nan.

I have not digged into how L is calculated from the RNN output from unrolling, just hope it helps.

### Alternative
For those who would like to work on multivariate time series, you may try using `LowrankMultivariateGaussianOutput`.
Below codes run successfully.

```
import numpy as np

from gluonts.dataset.common import ListDataset
from gluonts.distribution import LowrankMultivariateGaussianOutput
from gluonts.model.deepar import DeepAREstimator
from gluonts.trainer import Trainer

train_dataset = ListDataset(
    data_iter=[
        {
            "start": "2019-01-01 00:00:00",
            "target": np.ones(shape=(4, 100)).tolist(),
        },
    ],
    freq="5min",
    one_dim_target=False,
)

estimator = DeepAREstimator(
    'H', prediction_length=5, trainer=Trainer(epochs=3, hybridize=False),
    distr_output=LowrankMultivariateGaussianOutput(dim=4, rank=3),
)

predictor = estimator.train(train_dataset)
```

**Comment by lostella** [comment]
@davidlkl thanks for looking into this. I think having

```
    def lower_triangular_ones(self, F, d: int) -> Tensor:
        mask = F.zeros_like(F.eye(d))
        for k in range(1, d):
            mask = mask + F.eye(d, d, -k)
        return mask
```

would be more precise, and letting the offset `1` be customizable even better. I'm opening a PR where this utility function is moved to a more appropriate place, and implement the fix. Thanks!
