### ISSUE TITLE
Recipes give no `target` key error

### ISSUE THREAD

**Issue by quancore** [awslabs/gluon-ts#1607]
## Description
We have upgraded the library from 0.6.5 to 0.8.0 and it gives a key error.

## To Reproduce
```python
from gluonts.dataset.artificial import recipe as rcp
recipes = {
    'weekly_season_trend': [
        ("slope", rcp.RandomUniform(low=0, high=3, shape=(1,))),
        ("trend", rcp.LinearTrend(slope="slope")),
        ("daily_smooth_seasonality", rcp.SmoothSeasonality(period=7, phase=-72)),
        ("noise", rcp.RandomGaussian(stddev=0.1)),
        ("target", rcp.Add(["trend", "daily_smooth_seasonality", "noise"]))
    ],
}
recipe_anomaly = {
    'bmc_scale_anomalies': [
        ('normal_indicator', rcp.BinaryMarkovChain(one_to_zero=1 / (10), zero_to_one=0.3)),
        ('anomaly_indicator', rcp.OneMinus('normal_indicator')),
        ('anomaly_scale', rcp.RandomInteger(0, 20.0)),
        ('anomaly_multiplier', rcp.Ref('anomaly_scale') * rcp.Ref('anomaly_indicator')),
        ('target', rcp.Mul(['target', 'anomaly_multiplier']))
    ]
}
recipes['erratic'] = recipes['weekly_season_trend'] + recipe_anomaly['bmc_scale_anomalies']
date = datetime.datetime(2018, 1, 1).timestamp()
ts = next(rcp.generate(10, recipes['erratic'], pd.Timestamp(date), {}))
```

## Error message or code output
(Paste the complete error message, including stack trace, or the undesired output that the above snippet produces.)

```
Error
Traceback (most recent call last):
  File "/home/baran/PycharmProjects/anofox/packages/component_default/anofox/dataset/artificial_datasets_test.py", line 91, in test_reprod_recipe_err
    ts = next(rcp.generate(10, recipes['erratic'], pd.Timestamp(date), {}))
  File "/home/baran/PycharmProjects/anofox/.tox/component_default/lib/python3.8/site-packages/gluonts/dataset/artificial/recipe.py", line 80, in generate
    data = evaluate(recipe, length=length, global_state=global_state)
  File "/home/baran/PycharmProjects/anofox/.tox/component_default/lib/python3.8/site-packages/gluonts/dataset/artificial/recipe.py", line 139, in evaluate
    data[k] = resolve(
  File "/home/baran/PycharmProjects/anofox/.tox/component_default/lib/python3.8/site-packages/gluonts/dataset/artificial/recipe.py", line 48, in resolve
    r = val_or_callable(context, *args, **kwargs)
  File "/home/baran/PycharmProjects/anofox/.tox/component_default/lib/python3.8/site-packages/gluonts/dataset/artificial/recipe.py", line 832, in __call__
    [resolve(k, x, length, *args, **kwargs) for k in self.inputs],
  File "/home/baran/PycharmProjects/anofox/.tox/component_default/lib/python3.8/site-packages/gluonts/dataset/artificial/recipe.py", line 832, in <listcomp>
    [resolve(k, x, length, *args, **kwargs) for k in self.inputs],
  File "/home/baran/PycharmProjects/anofox/.tox/component_default/lib/python3.8/site-packages/gluonts/dataset/artificial/recipe.py", line 54, in resolve
    return context[val_or_callable]
KeyError: 'target'
```

## Environment
- Operating system: Ubuntu 21.04
- Python version: 3.8.6
- GluonTS version: 0.8.0
- MXNet version: 1.8.0.post0

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by lostella** [comment]
This is also not working on the `v0.7.x` branch, so it's something coming from a previous release apparently

@jgasthaus @vafl any clues on this?

**Comment by quancore** [comment]
Any update for this issue @jgasthaus @vafl ?
