### ISSUE TITLE
PyTorch version of NegativeBinomialOutput doesn't work

### ISSUE THREAD

**Issue by fernandocamargoai** [awslabs/gluon-ts#1646]
## Description
I've been using DeepAR's PyTorch version from [pytorch-ts](https://github.com/zalandoresearch/pytorch-ts) and when starting a new project, I decided to give the new official DeepAR's PyTorch version from GluonTS. Since I'm forecasting demand, I'm using NegativeBinomial.

## To Reproduce
Train DeepAR with NegativeBinomialOutput.

## Error message or code output

```
Traceback (most recent call last):
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/luigi/worker.py", line 191, in run
    new_deps = self._run_get_new_deps()
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/luigi/worker.py", line 133, in _run_get_new_deps
    task_gen = self.task.run()
  File "/home/fernando/datascience_workspace/ml-challenge/ml_challenge/task/training.py", line 191, in run
    train_output = estimator.train_model(
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/gluonts/torch/model/estimator.py", line 155, in train_model
    trainer.fit(
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 918, in _run
    self._dispatch()
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 996, in run_stage
    return self._run_train()
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1045, in _run_train
    self.fit_loop.run()
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 131, in advance
    batch_output = self.batch_loop.run(batch, self.iteration_count, self._dataloader_idx)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 100, in run
    super().run(batch, batch_idx, dataloader_idx)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 147, in advance
    result = self._run_optimization(batch_idx, split_batch, opt_idx, optimizer)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 201, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 394, in _optimizer_step
    model_ref.optimizer_step(
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1593, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 209, in step
    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 129, in __optimizer_step
    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 296, in optimizer_step
    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 303, in run_optimizer_step
    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 226, in optimizer_step
    optimizer.step(closure=lambda_closure, **kwargs)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/torch/optim/adam.py", line 66, in step
    loss = closure()
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 235, in _training_step_and_backward_closure
    result = self.training_step_and_backward(split_batch, batch_idx, opt_idx, optimizer, hiddens)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 533, in training_step_and_backward
    result = self._training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 306, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 193, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 172, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/gluonts/torch/model/deepar/lightning_module.py", line 82, in training_step
    train_loss = self._compute_loss(batch)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/gluonts/torch/model/deepar/lightning_module.py", line 57, in _compute_loss
    distr = self.model.output_distribution(params, scale)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/gluonts/torch/model/deepar/module.py", line 163, in output_distribution
    return self.distr_output.distribution(sliced_params, scale=scale)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/gluonts/torch/modules/distribution_output.py", line 139, in distribution
    distr = self.distr_cls(*distr_args)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/torch/distributions/negative_binomial.py", line 39, in __init__
    super(NegativeBinomial, self).__init__(batch_shape, validate_args=validate_args)
  File "/mnt/hdd/anaconda3/envs/ml-challenge/lib/python3.8/site-packages/torch/distributions/distribution.py", line 53, in __init__
    raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter probs has invalid values

```

## Environment
- Operating system: Manjaro
- Python version: 3.8
- GluonTS version: 0.8
- PyTorch version: 1.9

**Comment by fernandocamargoai** [comment]
As a workaround, I've installed [pytorch-ts](https://github.com/zalandoresearch/pytorch-ts) and passed their implementation of `NegativeBinomialOutput` to `DeepAREstimator`.

**Comment by mbohlkeschneider** [comment]
Thank you for raising this issue. Can you provide a snipped to reproduce the error? That would be great. Thank you!

**Comment by fernandocamargoai** [comment]
Hello, @mbohlkeschneider. Sorry for taking this long to answer. I couldn't find time to prepare a code snippet yet to reproduce the error, but simply using `NegativeBinomialOutput` in any PyTorch training code should be enough, simply it's using the wrong `NegativeBinomial` signature. I'm pretty sure you can simply pick [this example](https://ts.gluon.ai/tutorials/forecasting/howto_pytorch_lightning.html) and change from `StudentTOutput` to  `NegativeBinomialOutput` and the error would certainly happen.

**Comment by lostella** [comment]
Indeed: looks like the `NegativeBinomialOutput` class is [feeding positional arguments](https://github.com/awslabs/gluon-ts/blob/da3fbec871ad722753d275bff945dae29c3b9319/src/gluonts/torch/modules/distribution_output.py#L137), the second of which is assumed to be probabilities (see [here](https://pytorch.org/docs/stable/distributions.html#negativebinomial)) but [logits are provided instead](https://github.com/awslabs/gluon-ts/blob/da3fbec871ad722753d275bff945dae29c3b9319/src/gluonts/torch/modules/distribution_output.py#L273-L279). Interestingly, tests do not catch this.

**Comment by lostella** [comment]
@fernandocamargoai the issue is solved on the `master` branch, feel free to confirm (or disconfirm 😄)

**Comment by fernandocamargoai** [comment]
Thank you, @lostella!
