### ISSUE TITLE
orjson breaks TrainDataset.save()

### ISSUE THREAD

**Issue by verdimrc** [awslabs/gluon-ts#1708]
## Description
gluonts-0.8 recommends `orjson` or `ujson`. However, `orjson` breaks `TrainDataset.save()` with error `AttributeError: 'bytes' object has no attribute 'encode'`.

## To Reproduce
Minimal example of code snippet that reproduces the error:

```python
from gluonts.dataset.common import ListDataset, MetaData, TrainDatasets
from gluonts.dataset.field_names import FieldName

train_data = ListDataset(
    [
        {FieldName.TARGET: [3] * 4, FieldName.START: '2021-01-01'},
        {FieldName.TARGET: [7] * 4, FieldName.START: '2021-01-01'},
    ],
    freq='D',
)

test_data = ListDataset(
    [
        {FieldName.TARGET: [3] * 4, FieldName.START: '2021-01-01'},
        {FieldName.TARGET: [7] * 4, FieldName.START: '2021-01-01'},
    ],
    freq='D',
)

gluonts_datasets = TrainDatasets(
    metadata=MetaData(freq='D', target={'name': 'quantity'}, prediction_length = 2),
    train=train_data,
    test=test_data,
)

gluonts_datasets.save(path_str='/tmp/test-savedata', overwrite=True)
```

Steps to reproduce the error on a SageMaker notebook instance:

```bash
$ conda activate mxnet_latest_p37
$ pip install orjson 'gluonts~=0.8'
$ python <the python file above>
```

## Error message or code output

```
(mxnet_latest_p37) [ec2-user@ip-172-16-22-147 SageMaker]$ python test-json.py
Traceback (most recent call last):
  File "test-json.py", line 26, in <module>
    gluonts_datasets.save(path_str='/tmp/test-savedata', overwrite=True)
  File "/home/ec2-user/anaconda3/envs/mxnet_latest_p37/lib/python3.7/site-packages/gluonts/dataset/common.py", line 129, in save
    dump_line(f, self.metadata.dict())
  File "/home/ec2-user/anaconda3/envs/mxnet_latest_p37/lib/python3.7/site-packages/gluonts/dataset/common.py", line 124, in dump_line
    f.write(json.dumps(line).encode("utf-8"))
AttributeError: 'bytes' object has no attribute 'encode'
```

## Environment
- Operating system: SageMaker notebook instance
- Python version: 3.7.10
- GluonTS version: 0.8.1
- MXNet version: 1.7.0

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by jaheba** [comment]
Thanks for pointing this out!

Looks like `orjson` already emits `bytes`.

Maybe we should streamline our `json` wrappers to all either emit `bytes` or `str`. Alternatively, we could make this an option.
