### ISSUE TITLE
MXNetError when training Deep Renewal Process model

### ISSUE THREAD

**Issue by dat181197** [awslabs/gluon-ts#1725]
## Description
Hi team, thank you for a great library
I am working a project for demand forecasting on a custom dataset. I have managed to create a custom GluonTS dataset and successfully ran the DeepAR model on it. But when I tried to run the Deep Renewal Process model, I received the following error after one epoch of training. I have been trying to figure out the error, but have not found anything. 

Also I think there has been a change to the GluonTS framework that removed the `decode_fn` of the validation_dataloader in[ #1408](https://github.com/awslabs/gluon-ts/pull/1408), but in the [create_validation_data_loader function](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/model/renewal/_estimator.py#L242) of the model I still see "decode_fn" being returned which lead to an error when trying to use `model.train(train_ds, test_ds)`

https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/model/renewal/_estimator.py

```python
Starting training...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:02<00:00, 44.01it/s, epoch=1/30, avg_epoch_loss=0.771]
 65%|███████████████████████████████████████████████████████████████████████████████████▏                                            | 65/100 [00:01<00:00, 41.55it/s, epoch=2/30, avg_epoch_loss=0.341]
Traceback (most recent call last):
  File "src/train_DRP.py", line 82, in <module>
    train(cfg)
  File "src/train_DRP.py", line 54, in train
    predictor = model.train(train_ds)
  File "/data10TB/datduong_research/PlayMaker/playmaker-model-pipeline/venv/lib/python3.8/site-packages/gluonts/mx/model/estimator.py", line 195, in train
    return self.train_model(
  File "/data10TB/datduong_research/PlayMaker/playmaker-model-pipeline/venv/lib/python3.8/site-packages/gluonts/mx/model/estimator.py", line 170, in train_model
    self.trainer(
  File "/data10TB/datduong_research/PlayMaker/playmaker-model-pipeline/venv/lib/python3.8/site-packages/gluonts/mx/trainer/_base.py", line 436, in __call__
    epoch_loss = loop(
  File "/data10TB/datduong_research/PlayMaker/playmaker-model-pipeline/venv/lib/python3.8/site-packages/gluonts/mx/trainer/_base.py", line 356, in loop
    output = net(*batch.values())
  File "/data10TB/datduong_research/PlayMaker/playmaker-model-pipeline/venv/lib/python3.8/site-packages/mxnet/gluon/block.py", line 682, in __call__
    out = self.forward(*args)
  File "/data10TB/datduong_research/PlayMaker/playmaker-model-pipeline/venv/lib/python3.8/site-packages/mxnet/gluon/block.py", line 1299, in forward
    return self._call_cached_op(x, *args)
  File "/data10TB/datduong_research/PlayMaker/playmaker-model-pipeline/venv/lib/python3.8/site-packages/mxnet/gluon/block.py", line 1078, in _call_cached_op
    out = self._cached_op(*cargs)
  File "/data10TB/datduong_research/PlayMaker/playmaker-model-pipeline/venv/lib/python3.8/site-packages/mxnet/_ctypes/ndarray.py", line 148, in __call__
    check_call(_LIB.MXInvokeCachedOpEx(
  File "/data10TB/datduong_research/PlayMaker/playmaker-model-pipeline/venv/lib/python3.8/site-packages/mxnet/base.py", line 246, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: MXNetError: Error in operator deeprenewaltrainingnetwork0_slice_axis1: [18:19:15] ../src/operator/tensor/./matrix_op-inl.h:1296: Check failed: (*begin < *end): Invalid begin, end, get begin=0, end=-1
```

It would be nice if you guys could help me fix this issues. Thank you!

## Environment
- Operating system: Ubuntu 18.04
- Python version: 3.8.11
- GluonTS version: 0.8.1
- MXNet version: 1.8.0.post0

**Comment by canerturkmen** [comment]
Hi @dat181197 , thanks for your comment.

Unfortunately, I still cannot reproduce the error, after having tried setting the distribution outputs to both Poisson and NegativeBinomial. Moreover, as the hyperparameters you provide in the example are not concrete values (they are set to some configuration not in the code I believe), I can't pinpoint what's causing the issue. 

I understand you cannot provide the data set, but perhaps could you provide an end-to-end example, with concrete hyperparameter values and a synthetic data set (also produced within the MWE) that reproduces this issue? I don't think we can diagnose the root cause otherwise. 

Thanks!

**Comment by ZenBel** [comment]
Hello,

I have a similar problem as @dat181197. The fix in [this branch](https://github.com/canerturkmen/gluon-ts/tree/fix-deep-renewal) fixes the problem during training but not during inference.

Here is a MWE and a [dataset](https://github.com/awslabs/gluon-ts/files/7528905/gluonTSdata.zip) to reproduce it:

```
from gluonts.dataset.common import load_datasets

dataset = load_datasets(
    metadata='../data/gluonTSdata/metadata',
    train='../data/gluonTSdata/train',
    test='../data/gluonTSdata/test',
)

from gluonts.model.renewal import DeepRenewalProcessEstimator
from gluonts.mx import Trainer
from gluonts.mx.distribution import NegativeBinomialOutput
from gluonts.evaluation import make_evaluation_predictions
import mxnet as mx
import numpy as np
mx.random.seed(42)
np.random.seed(42)

trainer = Trainer(
        ctx="cpu",
        epochs=50,
        num_batches_per_epoch=15,
        batch_size=32,
        learning_rate=1e-3,
        learning_rate_decay_factor=0.5,
        patience=10,
        minimum_learning_rate=5e-5,
        clip_gradient=10,
        weight_decay=1e-8,
        init="xavier"
    )

estimator = DeepRenewalProcessEstimator(
    freq=dataset.metadata.freq,
    prediction_length=dataset.metadata.prediction_length,
    context_length=52,
    num_layers=1,
    num_cells=20,
    dropout_rate=0.1,
    interval_distr_output=NegativeBinomialOutput(),
    size_distr_output=NegativeBinomialOutput(),
    trainer=trainer
)

predictor = estimator.train(dataset.train)

forecast_it, ts_it = make_evaluation_predictions(
    dataset=dataset.test,  
    predictor=predictor,  
    num_samples=200, 
)

forecasts = list(forecast_it)
tss = list(ts_it)
```

Here is the error:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/var/folders/fr/ysw55r550qvg0966gg0v67z80000gn/T/ipykernel_8704/3227958063.py in <module>
      1 # Convert generators to lists
----> 2 forecasts = list(forecast_it)
      3 tss = list(ts_it)

~/Library/Caches/pypoetry/virtualenvs/time-series-NsJXeOEt-py3.8/lib/python3.8/site-packages/gluonts/model/renewal/_predictor.py in predict(self, dataset, num_samples, **kwargs)
    116         )
    117         with mx.Context(self.ctx):
--> 118             yield from self.forecast_generator(
    119                 inference_data_loader=inference_data_loader,
    120                 prediction_net=self.prediction_net,

~/Library/Caches/pypoetry/virtualenvs/time-series-NsJXeOEt-py3.8/lib/python3.8/site-packages/gluonts/model/forecast_generator.py in __call__(self, inference_data_loader, prediction_net, input_names, freq, output_transform, num_samples, **kwargs)
    174             outputs = predict_to_numpy(prediction_net, inputs)
    175             if output_transform is not None:
--> 176                 outputs = output_transform(batch, outputs)
    177             if num_samples:
    178                 num_collected_samples = outputs[0].shape[0]

~/Library/Caches/pypoetry/virtualenvs/time-series-NsJXeOEt-py3.8/lib/python3.8/site-packages/gluonts/model/renewal/_predictor.py in __call__(self, entry, output)
     57             ix = t[t < max_time].astype(int).tolist()
     58             if len(ix) > 0:
---> 59                 out[i, j, ix] = s[: len(ix)]
     60 
     61         return out

IndexError: index -18 is out of bounds for axis 2 with size 8
```

**Comment by canerturkmen** [comment]
Hi @ZenBel, thanks a lot for the MWE, it was very helpful indeed. I pushed a new fix to https://github.com/canerturkmen/gluon-ts/tree/fix-deep-renewal, could you check if it is helpful?
(cc @dat181197)

**Comment by ZenBel** [comment]
Thanks @canerturkmen, the fix works like a charm!

**Comment by dat181197** [comment]
Hi @canerturkmen, thanks for the fix, it works on my side as well.
Thank you @ZenBel for providing the MWE, I could not manage to create one, unfortunately.

I will close this issue for now, thank you!

**Comment by deifeb** [comment]
Hello, I also have a problem like yours, how did you solve it?（mxnet.base.MXNetError: MXNetError: Error in operator deeprenewaltrainingnetwork0_slice_axis1: [18:19:15] ../src/operator/tensor/./matrix_op-inl.h:1296: Check failed: (*begin < *end): Invalid begin, end, get begin=0, end=-1）
