### ISSUE TITLE
Error with multiple-month frequency when data is misaligned

### ISSUE THREAD

**Issue by lostella** [awslabs/gluon-ts#1912]
## Description
A problem occurs when a dataset with frequency which is multiple months is fed to a model, and the series are not "aligned" according to the frequency. For example (see reproducing snippet below), when using `freq="2M"` and there are two series:
* training works fine if the two series start at, respectively
    * `"2021-01-01"`
    * `"2021-03-01"` (or any other date which is a multiple of 2 months away from the previous)
* training **breaks** if the two series start at, respectively
    * `"2021-01-01"`
    * `"2021-02-01"` (or any other date which is **not** a multiple of 2 months away from the previous)

## To Reproduce

```python
from gluonts.dataset.common import ListDataset
from gluonts.model.deepar import DeepAREstimator
from gluonts.mx.trainer import Trainer

dataset = ListDataset(
    data_iter=[
        {"start": "2021-01-01 00:00:00", "target": [1.0] * 20},
        {"start": "2021-02-01 00:00:00", "target": [1.0] * 20}
    ],
    freq="2M"
)

estimator = DeepAREstimator(
    freq="2M", prediction_length=4, context_length=10,
    trainer=Trainer(epochs=5)
)

predictor = estimator.train(dataset)
```

## Error message or code output

```
Traceback (most recent call last):
  File "pandas/_libs/index.pyx", line 444, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1625, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1632, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 1614470400000000000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xyz/.virtualenvs/gluonts/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 413, in pandas._libs.index.DatetimeEngine.get_loc
  File "pandas/_libs/index.pyx", line 446, in pandas._libs.index.DatetimeEngine.get_loc
KeyError: Timestamp('2021-02-28 00:00:00', freq='2M')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xyz/.virtualenvs/gluonts/lib/python3.7/site-packages/pandas/core/indexes/datetimes.py", line 686, in get_loc
    return Index.get_loc(self, key, method, tolerance)
  File "/Users/xyz/.virtualenvs/gluonts/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: Timestamp('2021-02-28 00:00:00', freq='2M')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "reproduce.py", line 18, in <module>
    predictor = estimator.train(dataset)
  File "/Users/xyz/gluon-ts/src/gluonts/mx/model/estimator.py", line 233, in train
    cache_data=cache_data,
  File "/Users/xyz/gluon-ts/src/gluonts/mx/model/estimator.py", line 186, in train_model
    shuffle_buffer_length=shuffle_buffer_length,
  File "/Users/xyz/gluon-ts/src/gluonts/model/deepar/_estimator.py", line 403, in create_training_data_loader
    with env._let(max_idle_transforms=maybe_len(data) or 0):
  File "/Users/xyz/gluon-ts/src/gluonts/itertools.py", line 23, in maybe_len
    return len(obj)
  File "/Users/xyz/gluon-ts/src/gluonts/transform/_base.py", line 101, in __len__
    return sum(1 for _ in self)
  File "/Users/xyz/gluon-ts/src/gluonts/transform/_base.py", line 101, in <genexpr>
    return sum(1 for _ in self)
  File "/Users/xyz/gluon-ts/src/gluonts/transform/_base.py", line 105, in __iter__
    self.base_dataset, is_train=self.is_train
  File "/Users/xyz/gluon-ts/src/gluonts/transform/_base.py", line 124, in __call__
    for data_entry in data_it:
  File "/Users/xyz/gluon-ts/src/gluonts/transform/_base.py", line 124, in __call__
    for data_entry in data_it:
  File "/Users/xyz/gluon-ts/src/gluonts/transform/_base.py", line 128, in __call__
    raise e
  File "/Users/xyz/gluon-ts/src/gluonts/transform/_base.py", line 126, in __call__
    yield self.map_transform(data_entry.copy(), is_train)
  File "/Users/xyz/gluon-ts/src/gluonts/transform/feature.py", line 373, in map_transform
    i0 = self._date_index[start]
  File "/Users/xyz/.virtualenvs/gluonts/lib/python3.7/site-packages/pandas/core/series.py", line 853, in __getitem__
    return self._get_value(key)
  File "/Users/xyz/.virtualenvs/gluonts/lib/python3.7/site-packages/pandas/core/series.py", line 961, in _get_value
    loc = self.index.get_loc(label)
  File "/Users/xyz/.virtualenvs/gluonts/lib/python3.7/site-packages/pandas/core/indexes/datetimes.py", line 688, in get_loc
    raise KeyError(orig_key) from err
KeyError: Timestamp('2021-02-28 00:00:00', freq='2M')
```

## Environment
- Operating system: macos
- Python version: 3.7
- GluonTS version: `master`
- MXNet version: 1.8.0
- Pandas version: 1.2.4

**Comment by lostella** [comment]
Breaking down the problem a bit. Data is set up like in the OP:

```python
from gluonts.dataset.common import ListDataset

dataset = ListDataset(
    data_iter=[
        {"start": "2021-01-01 00:00:00", "target": [1.0] * 20},
        {"start": "2021-02-01 00:00:00", "target": [1.0] * 20}
    ],
    freq="2M"
)
```

Printing it reveals the timestamp "massaging" that happens:

```

**Comment by melopeo** [comment]
My very small grain of salt. 
This is potentially related to the notion of `offsets` when dealing with dates. For the very particular case of bimonthly data there is an example on how offsets can be handled: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#using-offsets-with-series-datetimeindex

On the other side, if the issue is only by the fact of having bimonthly data on the beginning of the corresponding months, then the `offset` can be handled via `freq='MS'` where MS stands for `"month start frequency"` (https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases)

**Comment by lostella** [comment]
It is related with offset, for sure. However, what breaks in the example above is the construction of features as @jaheba identified. `AddTimeFeatures` transformation has a baked-in assumption that all given time series start at points which are `k * freq` away from each other, for some integer `k`: we have some magic in place, that tries to "align" start timestamps from each series, so that they all satisfy such assumption and features can be computed fine. It just happens that for multiples of months (and potentially other frequencies) such magic does not work as expected and `AddTimeFeatures` has trouble working.

I believe the assumption is used for performance reasons, so that `AddTimeFeatures` can cache a lot of stuff: in the extreme case where all time series span exactly the same time range, you'll be essentially computing all features once and for all.

I see two solutions:
1. Improve the "alignment" of start timestamps, so that it works on these more complex frequencies too. That is to say, when given the "broken" example in my previous post, the second time series has its start timestamp shifted to something which is `k * 2 * months` away from the other series (end of January just like the first series, or end of March).
2. Improve the caching logic of `AddTimeFeatures` so that it doesn't break. This means that the timestamp alignment can stay as it is now, which makes sense the more I think of it (why should a data point that refers to February be moved to March or January? Even if data was aggregated bi-monthly, some series can start in January and some in February, and their forecasts will be shifted by a month and that should be fine)

I tend to think that 2 is the better solution among the two.
