### ISSUE TITLE
PyTorch DataLoader not working

### ISSUE THREAD

**Issue by Poulami-Sarkar** [awslabs/gluon-ts#1988]
## PyTorch DataLoader not working
I am trying to re-create the gluonTS tutorial for the m5 dataset using the GluonTS PyTorch model. However, the PyTorch GluonTS data loader (gluonts.torch.model.deepar.estimator.DeepAREstimator .create_training_data_loader) gives me an empty iterable.
 
 Can someone kindly help me with this issue? 

## To Reproduce

```python

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json
import os
from tqdm import tqdm
from pathlib import Path
from gluonts.dataset.common import load_datasets, ListDataset
from gluonts.dataset.field_names import FieldName

from gluonts.torch.model.deepar import DeepARModel
from gluonts.torch.model.deepar.estimator import DeepAREstimator
from gluonts.torch.modules.distribution_output import NegativeBinomialOutput
import pytorch_lightning as pl


single_prediction_length = 28
submission_prediction_length = single_prediction_length * 2
m5_input_path="./Data/m5-forecasting-accuracy"
submission=False

if submission:
    prediction_length = submission_prediction_length
else:
    prediction_length = single_prediction_length

calendar = pd.read_csv(m5_input_path+'/calendar.csv')
sales_train_validation = pd.read_csv(m5_input_path+'/sales_train_validation.csv')
sample_submission = pd.read_csv(m5_input_path+'/sample_submission.csv')
sell_prices = pd.read_csv(m5_input_path+'/sell_prices.csv')

cal_features = calendar.drop(
    ['date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'event_name_1', 'event_name_2', 'd'], 
    axis=1
)
cal_features['event_type_1'] = cal_features['event_type_1'].apply(lambda x: 0 if str(x)=="nan" else 1)
cal_features['event_type_2'] = cal_features['event_type_2'].apply(lambda x: 0 if str(x)=="nan" else 1)

test_cal_features = cal_features.values.T
if submission:
    train_cal_features = test_cal_features[:,:-submission_prediction_length]
else:
    train_cal_features = test_cal_features[:,:-submission_prediction_length-single_prediction_length]
    test_cal_features = test_cal_features[:,:-submission_prediction_length]

test_cal_features_list = [test_cal_features] * len(sales_train_validation)
train_cal_features_list = [train_cal_features] * len(sales_train_validation)

state_ids = sales_train_validation["state_id"].astype('category').cat.codes.values
state_ids_un , state_ids_counts = np.unique(state_ids, return_counts=True)

store_ids = sales_train_validation["store_id"].astype('category').cat.codes.values
store_ids_un , store_ids_counts = np.unique(store_ids, return_counts=True)

cat_ids = sales_train_validation["cat_id"].astype('category').cat.codes.values
cat_ids_un , cat_ids_counts = np.unique(cat_ids, return_counts=True)

dept_ids = sales_train_validation["dept_id"].astype('category').cat.codes.values
dept_ids_un , dept_ids_counts = np.unique(dept_ids, return_counts=True)

item_ids = sales_train_validation["item_id"].astype('category').cat.codes.values
item_ids_un , item_ids_counts = np.unique(item_ids, return_counts=True)

stat_cat_list = [item_ids, dept_ids, cat_ids, store_ids, state_ids]

stat_cat = np.concatenate(stat_cat_list)
stat_cat = stat_cat.reshape(len(stat_cat_list), len(item_ids)).T

stat_cat_cardinalities = [len(item_ids_un), len(dept_ids_un), len(cat_ids_un), len(store_ids_un), len(state_ids_un)]



train_df = sales_train_validation.drop(["id","item_id","dept_id","cat_id","store_id","state_id"], axis=1)
train_target_values = train_df.values

if submission == True:
    test_target_values = [np.append(ts, np.ones(submission_prediction_length) * np.nan) for ts in train_df.values]
else:
    test_target_values = train_target_values.copy()
    train_target_values = [ts[:-single_prediction_length] for ts in train_df.values]

m5_dates = [pd.Timestamp("2011-01-29", freq='1D') for _ in range(len(sales_train_validation))]

train_ds = ListDataset([
    {
        FieldName.TARGET: target,
        FieldName.START: start,
        FieldName.FEAT_DYNAMIC_REAL: fdr,
        FieldName.FEAT_STATIC_CAT: fsc
    }
    for (target, start, fdr, fsc) in zip(train_target_values,
                                         m5_dates,
                                         train_cal_features_list,
                                         stat_cat)
], freq="D")

test_ds = ListDataset([
    {
        FieldName.TARGET: target,
        FieldName.START: start,
        FieldName.FEAT_DYNAMIC_REAL: fdr,
        FieldName.FEAT_STATIC_CAT: fsc
    }
    for (target, start, fdr, fsc) in zip(test_target_values,
                                         m5_dates,
                                         test_cal_features_list,
                                         stat_cat)
], freq="D")

deepar = DeepAREstimator(
    prediction_length=prediction_length,
    freq="D",
    distr_output = NegativeBinomialOutput(),
    num_feat_dynamic_real=5,
    num_feat_static_cat=5,
    cardinality=stat_cat_cardinalities,
    batch_size=32,
)

model = deepar.create_lightning_module()


train_data_loader = deepar.create_training_data_loader(train_ds,model)

for i in iter(train_data_loader):
    print(I)

#### THIS FINAL PRINT STATEMENT GIVES ME A BLANK OUTPUT. 

```

## Environment
- Operating system: MACOS
- Python version: 3.9.12
- GluonTS version: 0.9.4

**Comment by lostella** [comment]
@Poulami-Sarkar on `gluonts` version `0.9.4` I'm actually getting some other error:

```
Traceback (most recent call last):
  File "issues/1988/reproduce.py", line 127, in <module>
    for i in iter(train_data_loader):
  File "/Users/stellalo/.virtualenvs/gluonts/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/Users/stellalo/.virtualenvs/gluonts/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/Users/stellalo/.virtualenvs/gluonts/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 32, in fetch
    data.append(next(self.dataset_iter))
  File "/Users/stellalo/gluon-ts/src/gluonts/torch/util.py", line 94, in __iter__
    yield from self.iterable
  File "/Users/stellalo/gluon-ts/src/gluonts/transform/_base.py", line 105, in __iter__
    self.base_dataset, is_train=self.is_train
  File "/Users/stellalo/gluon-ts/src/gluonts/transform/_base.py", line 124, in __call__
    for data_entry in data_it:
  File "/Users/stellalo/gluon-ts/src/gluonts/transform/_base.py", line 179, in __call__
    for result in self.flatmap_transform(data_entry.copy(), is_train):
  File "/Users/stellalo/gluon-ts/src/gluonts/transform/split.py", line 165, in flatmap_transform
    past_piece = d[ts_field][..., i - self.past_length : i]
```

**Comment by lostella** [comment]
@Poulami-Sarkar what are you trying to do? If you just need to train the estimator on the dataset that you set up, you should just call

```python
deepar_predictor = deepar.train(train_ds)
```

But if you invoke other methods from the `DeepAREstimator` class, maybe you are trying to do something more custom? 

The reason I'm asking is: the error I'm getting [here](https://github.com/awslabs/gluon-ts/issues/1988#issuecomment-1139942276) is caused by the fact that the data is missing some field (`"time_feat"`) which the estimator internally adds to the dataset, through the transformation given by `DeepAREstimator.create_transformation`. In summary, these methods are meant to be used internally by the estimator, whose only "public" method really is `.train` currently. We may need to improve the inner workings of estimator classes however, hence I'm interested in your use case (in case `.train` is not what you are looking for).

**Comment by Poulami-Sarkar** [comment]
Hi,
Thanks a lot for your help. That worked for me.
