### ISSUE TITLE
Pytorch models are not serializable

### ISSUE THREAD

**Issue by rsnirwan** [awslabs/gluon-ts#2090]
## Description
Printing or serializing pytorch deepar estimator results into `RuntimeError`.
The problem is that `gluonts.torch.modules.loss.DistributionLoss` is not serializable.

## To Reproduce
```python
from gluonts.torch.model.deepar.estimator import DeepAREstimator
from gluonts.dataset.repository.datasets import get_dataset

dataset = get_dataset("m4_hourly")

model = DeepAREstimator(
    freq=dataset.metadata.freq,
    prediction_length=dataset.metadata.prediction_length,
    context_length=dataset.metadata.prediction_length,
)
print(model)
```

## Error message or code output
```
Traceback (most recent call last):
  File "p.py", line 11, in <module>
    print(model)
  File "/Users/nirwar/Dev/gitrepos/gluon-ts/src/gluonts/core/component.py", line 310, in validated_repr
    return dump_code(self)
  File "/Users/nirwar/Dev/gitrepos/gluon-ts/src/gluonts/core/serde/_repr.py", line 115, in dump_code
    return as_repr(encode(o))
  File "/Users/nirwar/.runtimes/Python38/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/nirwar/Dev/gitrepos/gluon-ts/src/gluonts/core/serde/_base.py", line 220, in encode
    "kwargs": encode(kwargs),
  File "/Users/nirwar/.runtimes/Python38/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/nirwar/Dev/gitrepos/gluon-ts/src/gluonts/core/serde/_base.py", line 207, in encode
    return valmap(encode, v)
  File "/Users/nirwar/.runtimes/Python38/lib/python3.8/site-packages/toolz/dicttoolz.py", line 83, in valmap
    rv.update(zip(d.keys(), map(func, d.values())))
  File "/Users/nirwar/.runtimes/Python38/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/nirwar/Dev/gitrepos/gluon-ts/src/gluonts/core/serde/_base.py", line 243, in encode
    raise RuntimeError(bad_type_msg.format(fqname_for(v.__class__)))
RuntimeError: Cannot serialize type gluonts.torch.modules.loss.NegativeLogLikelihood. See the documentation of the `encode` and
`validate` functions at

    http://gluon-ts.mxnet.io/api/gluonts/gluonts.html

and the Python documentation of the `__getnewargs_ex__` magic method at

    https://docs.python.org/3/library/pickle.html#object.__getnewargs_ex__

for more information how to make this type serializable.


shell returned 1
```

## Environment
- Operating system: macOS
- Python version: 3.8
- GluonTS version: current dev (9322d73)
- MXNet version: -

**Comment by jaheba** [comment]
We would need to make `gluonts.torch.modules.loss.DistributionLoss` compatible with `serde`.

The error message is a bit misleading, since we don't require `__getnewargs_ex__`.

We some logic to encode mxnet values here: https://github.com/awslabs/gluon-ts/blob/dev/src/gluonts/mx/serde.py

**Comment by jaheba** [comment]
On a second note, we actually just need to implement a compatible API for serde.

**Comment by jaheba** [comment]
I've spend too much time on this: #2092.
