### ISSUE TITLE
get_dataset function is broken with python3.9

### ISSUE THREAD

**Issue by rsnirwan** [awslabs/gluon-ts#2133]
## Description
A call to `get_dataset` with any dataset doesn't work with python3.9, but works with python 3.8.
The Error is in [DatasetCollection](https://github.com/awslabs/gluon-ts/blob/dev/src/gluonts/dataset/__init__.py#L37).
It might be the interplay of inheriting from `Protocol` and `dataclass` decorator as reported [here](https://stackoverflow.com/questions/69962929/passing-the-arguments-to-dataclass-causes-typeerror).

## To Reproduce

```python
from gluonts.dataset.repository.datasets import get_dataset
get_dataset("m4_hourly")
```

## Error message or code output
```
warnings.warn(
Traceback (most recent call last):
  File "/local/home/nirwar/tests/gts39error/p.py", line 2, in <module>
    get_dataset("m4_hourly")
  File "/local/home/nirwar/tests/gts39error/lib/python3.9/site-packages/gluonts/dataset/repository/datasets.py", line 332, in get_dataset
    return load_datasets(
  File "/local/home/nirwar/tests/gts39error/lib/python3.9/site-packages/gluonts/dataset/common.py", line 446, in load_datasets
    train_ds = FileDataset(
  File "/local/home/nirwar/tests/gts39error/lib/python3.9/site-packages/gluonts/dataset/common.py", line 183, in FileDataset
    return DatasetCollection(
TypeError: DatasetCollection() takes no arguments
```

## Environment
- Operating system: Amazon Linux and macOS
- Python version: 3.9.7 (3.8.13 works)
- GluonTS version: 0.10.0
- MXNet version: -

**Comment by jaheba** [comment]
There is no need to inherit from Dataset, since that's the idea behind Protocols: implicit membership. 

On the other hand the docs explicitly state that this is possible.
