### ISSUE TITLE
mqcnn on gpu: control dep not found in graph

### ISSUE THREAD

**Issue by mharvan** [awslabs/gluon-ts#2316]
Training mqcnn models on a gpu is consistently failing for me with the error
```
MXNetError: Check failed: it != node2index_.end(): control dep not found in graph
```

Complete error message:
```
$ python examples/benchmark_m4.py 
evaluating gluonts.model.seq2seq._mq_dnn_estimator.MQCNNEstimator(add_age_feature=False, add_time_feature=True, batch_size=32, cardinality=[414], channels_seq=None, context_length=None, decoder_mlp_dim_seq=None, dilation_seq=None, distr_output=None, embedding_dimension=None, enable_decoder_dynamic_feature=True, enable_encoder_dynamic_feature=True, freq="H", is_iqf=True, kernel_size_seq=None, max_ts_len=None, num_forking=None, prediction_length=48, quantiles=None, scaling=None, scaling_decoder_dynamic_feature=False, seed=None, trainer=gluonts.mx.trainer._base.Trainer(add_default_callbacks=True, batch_size=None, callbacks=None, clip_gradient=10.0, ctx=mxnet.context.Context("gpu", 0), epochs=100, hybridize=True, init="xavier", learning_rate=0.001, learning_rate_decay_factor=0.5, minimum_learning_rate=5e-05, num_batches_per_epoch=50, patience=10, weight_decay=1e-08), use_feat_dynamic_real=False, use_feat_static_cat=True, use_past_feat_dynamic_real=False, use_residual=True) on TrainDatasets(metadata=MetaData(freq='H', target=None, feat_static_cat=[CategoricalFeatureInfo(name='feat_static_cat', cardinality='414')], feat_static_real=[], feat_dynamic_real=[], feat_dynamic_cat=[], prediction_length=48), train=DatasetCollection(datasets=[Map(data=JsonLinesFile(path=PosixPath('/home/matus/.mxnet/gluon-ts/datasets/m4_hourly/train/data.json')))], interleave=False), test=DatasetCollection(datasets=[Map(data=JsonLinesFile(path=PosixPath('/home/matus/.mxnet/gluon-ts/datasets/m4_hourly/test/data.json')))], interleave=False))
[14:02:48] ../src/base.cc:79: cuDNN lib mismatch: linked-against version 8201 != compiled-against version 8101.  Set MXNET_CUDNN_LIB_CHECKING=0 to quiet this warning.
  0%|                                                                                                                                                                   | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "../3rdparty/tvm/nnvm/src/core/graph.cc", line 109
MXNetError: Check failed: it != node2index_.end(): control dep not found in graph
Traceback (most recent call last):
  File "examples/benchmark_m4.py", line 104, in <module>
    sub_df = df[
  File "/home/matus/miniconda3/envs/eng-gpu/lib/python3.8/site-packages/pandas/core/frame.py", line 3511, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/matus/miniconda3/envs/eng-gpu/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5796, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/matus/miniconda3/envs/eng-gpu/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5856, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['dataset', 'estimator', 'RMSE', 'mean_wQuantileLoss', 'MASE', 'sMAPE',\n       'OWA', 'MSIS'],\n      dtype='object')] are in the [columns]"
```

This output comes from a simplified version of benchmark_m4.py:
```diff
diff --git a/examples/benchmark_m4.py b/examples/benchmark_m4.py
index 84f442b..1844099 100644
--- a/examples/benchmark_m4.py
+++ b/examples/benchmark_m4.py
@@ -14,6 +14,10 @@
 """
 This example shows how to fit a model and evaluate its predictions.
 """
+import warnings
+warnings.simplefilter(action='once', category=FutureWarning)
+#warnings.simplefilter(action='ignore', category=FutureWarning)
+
 import pprint
 from functools import partial
 
@@ -28,22 +32,22 @@ from gluonts.mx.trainer import Trainer
 
 datasets = [
     "m4_hourly",
-    "m4_daily",
-    "m4_weekly",
-    "m4_monthly",
-    "m4_quarterly",
-    "m4_yearly",
+    # "m4_daily",
+    # "m4_weekly",
+    # "m4_monthly",
+    # "m4_quarterly",
+    # "m4_yearly",
 ]
 
 epochs = 100
 num_batches_per_epoch = 50
 estimators = [
     MQCNNEstimator,
-    DeepAREstimator,
-    partial(
-        DeepAREstimator,
-        distr_output=PiecewiseLinearOutput(8),
-    ),
+    # DeepAREstimator,
+    # partial(
+    #     DeepAREstimator,
+    #     distr_output=PiecewiseLinearOutput(8),
+    # ),
 ]
 
 
@@ -60,6 +64,7 @@ def evaluate(dataset_name, estimator):
         trainer=Trainer(
             epochs=epochs,
             num_batches_per_epoch=num_batches_per_epoch,
+            ctx="gpu",
         ),
     )
```

Details about my setup:
```
$ pip list | egrep "gluon|mxnet"
gluonts               0.10.6
mxnet-cu112           1.9.1
$ nvidia-smi 
[...]
| NVIDIA-SMI 470.82.00    Driver Version: 470.82.00    CUDA Version: 11.4     |
[...]
$ lsb_release -d
Description:    Ubuntu 20.04.3 LTS
```

**Comment by lostella** [comment]
@mharvan potentially related to #2264: a workaround there is to set `hybridize=False` when constructing the `Trainer`

**Comment by mharvan** [comment]
Thanks @lostella , gpu training works with `hybridize=False`.
