### ISSUE TITLE
Get `MXNetError: Check failed: to.IsDefaultData()` when using validation data in WaveNet

### ISSUE THREAD

**Issue by VictorJouault** [awslabs/gluon-ts#2403]
## Description
When trying to use validation data in WaveNet, I get the following error: 
```
MXNetError: Traceback (most recent call last):
  File "../src/ndarray/ndarray.cc", line 1146
MXNetError: Check failed: to.IsDefaultData():
```

## To Reproduce

The following code produces an error (see below).

```python
from gluonts.mx.model.wavenet import WaveNetEstimator
from gluonts.mx.trainer import Trainer
from gluonts.dataset.repository.datasets import get_dataset

dataset = get_dataset("m4_hourly")
estim = WaveNetEstimator(
    freq = 'H',
    prediction_length=2,
    trainer=Trainer(epochs = 4, num_batches_per_epoch = 10)
)
estim.train(dataset.train, dataset.test)
```

Note that the same code without the validation set does NOT produce an error:
```python
from gluonts.mx.model.wavenet import WaveNetEstimator
from gluonts.mx.trainer import Trainer
from gluonts.dataset.repository.datasets import get_dataset

dataset = get_dataset("m4_hourly")
estim = WaveNetEstimator(
    freq = 'H',
    prediction_length=2,
    trainer=Trainer(epochs = 4, num_batches_per_epoch = 10)
)
estim.train(dataset.train)
```

## Error message or code output

```
---------------------------------------------------------------------------
MXNetError                                Traceback (most recent call last)
<ipython-input-1-24de9e6a8a0f> in <module>
      9     trainer=Trainer(epochs = 10, num_batches_per_epoch = 20)
     10 )
---> 11 estim.train(dataset.train, dataset.test)

~/anaconda3/lib/python3.8/site-packages/gluonts/mx/model/estimator.py in train(self, training_data, validation_data, shuffle_buffer_length, cache_data, **kwargs)
    236         **kwargs,
    237     ) -> Predictor:
--> 238         return self.train_model(
    239             training_data=training_data,
    240             validation_data=validation_data,

~/anaconda3/lib/python3.8/site-packages/gluonts/mx/model/estimator.py in train_model(self, training_data, validation_data, from_predictor, shuffle_buffer_length, cache_data)
    220 
    221         with self.trainer.ctx:
--> 222             predictor = self.create_predictor(transformation, training_network)
    223 
    224         return TrainOutput(

~/anaconda3/lib/python3.8/site-packages/gluonts/mx/model/wavenet/_estimator.py in create_predictor(self, transformation, trained_network)
    388         prediction_network.initialize()
    389 
--> 390         copy_parameters(
    391             net_source=trained_network,
    392             net_dest=prediction_network,

~/anaconda3/lib/python3.8/site-packages/gluonts/mx/util.py in copy_parameters(net_source, net_dest, ignore_extra, allow_missing)
    112     ) as model_dir:
    113         model_dir_path = str(Path(model_dir) / "tmp_model")
--> 114         net_source.save_parameters(model_dir_path)
    115         net_dest.load_parameters(
    116             model_dir_path,

~/anaconda3/lib/python3.8/site-packages/mxnet/gluon/block.py in save_parameters(self, filename, deduplicate)
    450         arg_dict = {key: val._reduce() for key, val in params.items()}
    451         save_fn = _mx_npx.save if is_np_array() else ndarray.save
--> 452         save_fn(filename, arg_dict)
    453 
    454     def save_params(self, filename):

~/anaconda3/lib/python3.8/site-packages/mxnet/ndarray/utils.py in save(fname, data)
    275         raise ValueError("data needs to either be a NDArray, dict of str, NDArray pairs "
    276                          "or a list of NDarrays.")
--> 277     check_call(_LIB.MXNDArraySave(c_str(fname),
    278                                   mx_uint(len(handles)),
    279                                   handles,

~/anaconda3/lib/python3.8/site-packages/mxnet/base.py in check_call(ret)
    244     """
    245     if ret != 0:
--> 246         raise get_last_ffi_error()
    247 
    248 

MXNetError: Traceback (most recent call last):
  File "../src/ndarray/ndarray.cc", line 1146
MXNetError: Check failed: to.IsDefaultData(): 
```

## Environment
- Operating system: Linux
- Python version: 3.8.8
- GluonTS version: 0.11.1
- MXNet version: 1.9.1

**Comment by lostella** [comment]
@VictorJouault this appears to be a bug related to the `ModelAveraging` callback, which is used by default in the `Trainer` class. Turning off default callbacks with `add_default_callbacks=False` when constructing the `Trainer` gets rid of the issue.

On to finding what's actually causing it.

**Comment by lostella** [comment]
Something in the network changes with this line: https://github.com/awslabs/gluonts/blob/d5d897cd02b3aaa499f3c3632d3a18863b1a24e7/src/gluonts/mx/trainer/model_averaging.py#L310

Trying to save the network parameters (with `training_network.save_parameters(SOME_PATH)`) right before that line is fine; doing the same right after that line raises the exception as in the OP.

**Comment by VictorJouault** [comment]
Thanks for looking into this. I can confirm that on my side, using `add_default_callbacks=False` solves the issue.
However, I was using the LR Scheduler. Removing the `ModelAveraging` callback by itself doesn't seem to take care of the issue, as even with only the `LearningRateReduction` callback, the same exception is raised. Could it be linked?

**Comment by lostella** [comment]
> Could it be linked?

I’m not sure, I actually saw it working if just comment out the ModelAveraging callback from the default ones (and leave learning rate reduction in).

What I could find so far: the issue arises if the network is loaded back from a checkpoint after running in “prediction mode”: the next save will trigger the exception. This can be seen by adding the following lines in the training loop [here](https://github.com/awslabs/gluonts/blob/26bc701f6e49f9a71381beab272695939ceb8020/src/gluonts/mx/trainer/_base.py#L322)

```python
if not is_training:
    net.save_parameters(SOME_FILE_PATH)
    net.load_parameters(SOME_FILE_PATH)
    net.save_parameters(SOME_FILE_PATH)
```

The first save is just to store the parameters so we can load them back; the second save triggers the issue. This is rather strange.
