### ISSUE TITLE
Anomaly detection example plotting bug

### ISSUE THREAD

**Issue by Amrit-Bhaskar-abhask10** [awslabs/gluon-ts#2445]
## Description
Running the Anomaly detection example here: https://github.com/awslabs/gluonts/blob/dev/examples/anomaly_detection.py
This bug is with the `time_index` variable used in plotting. 

## To Reproduce
[Running this Anomaly detection example](https://github.com/awslabs/gluonts/blob/dev/examples/anomaly_detection.py)

```
        plt.fill_between(
            time_index,
            percentiles[0, i],
            percentiles[-1, i],
            alpha=0.5,
            label="80% CI predicted",
        )
        plt.plot(time_index, target[i], label="target")
        plt.axvline(time_index[t], alpha=0.5, color="r")
        plt.title(f"NLL: {nll[i, t]}")
        plt.legend()
        plt.show()
```

## Error message or code output

```
Traceback (most recent call last):
  File "/Users/amritbhaskar/miniconda3/envs/CIS515/lib/python3.8/site-packages/matplotlib/axis.py", line 1506, in convert_units
    ret = self.converter.convert(x, self.units, self)
  File "/Users/amritbhaskar/miniconda3/envs/CIS515/lib/python3.8/site-packages/pandas/plotting/_matplotlib/converter.py", line 235, in convert
    values = PeriodConverter._convert_1d(values, units, axis)
  File "/Users/amritbhaskar/miniconda3/envs/CIS515/lib/python3.8/site-packages/pandas/plotting/_matplotlib/converter.py", line 241, in _convert_1d
    raise TypeError("Axis must have `freq` set to convert to Periods")
TypeError: Axis must have `freq` set to convert to Periods

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "anomaly_detection.py", line 108, in <module>
    plt.fill_between(
  File "/Users/amritbhaskar/miniconda3/envs/CIS515/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2543, in fill_between
    return gca().fill_between(
  File "/Users/amritbhaskar/miniconda3/envs/CIS515/lib/python3.8/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/amritbhaskar/miniconda3/envs/CIS515/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 5252, in fill_between
    return self._fill_between_x_or_y(
  File "/Users/amritbhaskar/miniconda3/envs/CIS515/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 5158, in _fill_between_x_or_y
    ma.masked_invalid, self._process_unit_info(
  File "/Users/amritbhaskar/miniconda3/envs/CIS515/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 2521, in _process_unit_info
    axis.update_units(data)
  File "/Users/amritbhaskar/miniconda3/envs/CIS515/lib/python3.8/site-packages/matplotlib/axis.py", line 1454, in update_units
    self._update_axisinfo()
  File "/Users/amritbhaskar/miniconda3/envs/CIS515/lib/python3.8/site-packages/matplotlib/axis.py", line 1490, in _update_axisinfo
    self.set_default_intervals()
  File "/Users/amritbhaskar/miniconda3/envs/CIS515/lib/python3.8/site-packages/matplotlib/axis.py", line 2257, in set_default_intervals
    xmin, xmax = self.convert_units(info.default_limits)
  File "/Users/amritbhaskar/miniconda3/envs/CIS515/lib/python3.8/site-packages/matplotlib/axis.py", line 1508, in convert_units
    raise munits.ConversionError('Failed to convert value(s) to axis '
matplotlib.units.ConversionError: Failed to convert value(s) to axis units: (datetime.date(2000, 1, 1), datetime.date(2010, 1, 1))
```

## Environment
- Operating system: macOS 11.6.7
- Python version: 3.8.12
- GluonTS version: 0.11.1
- MXNet version: 1.9.1

**Comment by Amrit-Bhaskar-abhask10** [comment]
The bug was fixed with the latest merge.
