### ISSUE TITLE
DeepState crashes when trained on solar dataset

### ISSUE THREAD

**Issue by abdulfatir** [awslabs/gluon-ts#2794]
## Description
`DeepStateEstimator` crashes when trained on the `solar_nips` dataset. It looks like the reason is that the PSD constraint is not being satisfied for one of the matrices.

## To Reproduce

```python
import numpy as np
import mxnet as mx

from gluonts.mx import DeepStateEstimator
from gluonts.dataset.repository.datasets import get_dataset

np.random.seed(42)
mx.random.seed(42)

dataset = get_dataset("solar_nips")

model = DeepStateEstimator(
    dataset.metadata.freq,
    dataset.metadata.prediction_length,
    cardinality=[int(feat.cardinality) for feat in dataset.metadata.feat_static_cat],
)
predictor = model.train(list(dataset.train), cache_data=True)

```

## Error message or code output

```
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [02:58<00:00,  3.57s/it, epoch=1/100, avg_epoch_loss=4.46]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [03:10<00:00,  3.82s/it, epoch=2/100, avg_epoch_loss=3.06]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [03:07<00:00,  3.74s/it, epoch=3/100, avg_epoch_loss=2.44]
 92%|███████████████████████████████████████████████████████████████████████████████████████████████████▎        | 46/50 [02:47<00:14,  3.65s/it, epoch=4/100, avg_epoch_loss=2.03]
Traceback (most recent call last):
  File "deepstate.py", line 17, in <module>
    predictor = model.train(list(dataset.train), cache_data=True)
  File "/Users/ansarnd/miniconda3/envs/gts-baselines/lib/python3.8/site-packages/gluonts/mx/model/estimator.py", line 237, in train
    return self.train_model(
  File "/Users/ansarnd/miniconda3/envs/gts-baselines/lib/python3.8/site-packages/gluonts/mx/model/estimator.py", line 214, in train_model
    self.trainer(
  File "/Users/ansarnd/miniconda3/envs/gts-baselines/lib/python3.8/site-packages/gluonts/mx/trainer/_base.py", line 420, in __call__
    epoch_loss = loop(
  File "/Users/ansarnd/miniconda3/envs/gts-baselines/lib/python3.8/site-packages/gluonts/mx/trainer/_base.py", line 323, in loop
    if not np.isfinite(ndarray.sum(loss).asscalar()):
  File "/Users/ansarnd/miniconda3/envs/gts-baselines/lib/python3.8/site-packages/mxnet/ndarray/ndarray.py", line 2590, in asscalar
    return self.asnumpy()[0]
  File "/Users/ansarnd/miniconda3/envs/gts-baselines/lib/python3.8/site-packages/mxnet/ndarray/ndarray.py", line 2568, in asnumpy
    check_call(_LIB.MXNDArraySyncCopyToCPU(
  File "/Users/ansarnd/miniconda3/envs/gts-baselines/lib/python3.8/site-packages/mxnet/base.py", line 246, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: Traceback (most recent call last):
  File "../src/operator/numpy/linalg/../../tensor/../linalg_impl.h", line 744
MXNetError: Check failed: ret == 0 (1 vs. 0) : spotrf failed in lapack on cpu. This may happen when the input matrix is either not symmetric or not positive definite.
```

## Environment
- Operating system: MacOS
- Python version: 3.8
- GluonTS version: 0.12.6
- MXNet version: 

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by abdulfatir** [comment]
cc @rshyamsundar
