### ISSUE TITLE
TemporalFusionTransformerEstimator gives error with previously unseen categorical feature during prediction

### ISSUE THREAD

**Issue by guti1** [awslabs/gluon-ts#2829]
## Description
The torch version of TFT seemingly does not play well during prediction with previously unseen categorical feature values, in the example below I have a categrocial feature in my dataset `color`; which could take 2 categories during in the train dataset. I set the `static_cardinalities` accordingly implicitly from the train dataset. During prediction an additional category appears as in a cold-start like scenario, and the prediction generation fails with an `IndexError` as the input to the Embedding layer to get the embeddings has an additional index. 

Maybe a possible workaround would be to set the cardinalities with additional possible values as `[len(cats) + possible_new_cats for cats in stats.feat_static_cat]`, however that feels a bit leeky as well.

## To Reproduce

```python
import numpy as np
import pandas as pd
import pytorch_lightning as pl
from gluonts.dataset.pandas import PandasDataset
from gluonts.dataset.stat import calculate_dataset_statistics
from gluonts.evaluation import make_evaluation_predictions
from gluonts.torch import TemporalFusionTransformerEstimator

np.random.seed(42)
pl.seed_everything(42)
#%%
def generate_single_ts(date_range, item_id=None) -> pd.DataFrame:
    """create sum of `n_f` sin/cos curves with random scale and phase."""
    n_f = 2
    period = np.array([24 / (i + 1) for i in range(n_f)]).reshape(1, n_f)
    scale = np.random.normal(1, 0.3, size=(1, n_f))
    phase = 2 * np.pi * np.random.uniform(size=(1, n_f))
    periodic_f = lambda x: scale * np.sin(np.pi * x / period + phase)

    t = np.arange(0, len(date_range)).reshape(-1, 1)
    target = periodic_f(t).sum(axis=1) + np.random.normal(0, 0.1, size=len(t))
    ts = pd.DataFrame({"target": target}, index=date_range)
    if item_id is not None:
        ts["item_id"] = item_id
    return ts


def generate_single_ts_with_features(date_range, item_id) -> pd.DataFrame:

    ts = generate_single_ts(date_range, item_id)
    T = ts.shape[0]
    # static features are constant for each series
    ts["dynamic_real_1"] = np.random.normal(size=T)
    ts["dynamic_real_2"] = np.random.normal(size=T)
    # ... we can have as many static or dynamic features as we like
    return ts


#%%
prediction_length, freq = 24, "1H"
T = 15 * prediction_length
date_range = pd.date_range("2021-01-01", periods=T, freq=freq)
ts = generate_single_ts(date_range)

N = 15

multiple_ts = {
    i: generate_single_ts_with_features(date_range, item_id=i) for i in range(N)
}
static_features = pd.DataFrame(
    {
        "color": np.random.choice(["red", "green", "blue"], size=N),
        "height": np.random.normal(loc=100, scale=15, size=N),
    },
    index=list(multiple_ts.keys()),
)
multiple_ts_long = pd.concat(multiple_ts.values()).reset_index()
multiple_ts_long = multiple_ts_long.rename(columns={"index": "date"})
multiple_ts_long["dynamic_real_1"] = multiple_ts_long["dynamic_real_1"].astype(
    np.float32
)
multiple_ts_long["dynamic_real_2"] = multiple_ts_long["dynamic_real_2"].astype(
    np.float32
)
multiple_ts_long = multiple_ts_long.merge(
    static_features.reset_index(), how="left", right_on="index", left_on="item_id"
)
multiple_ts_long = multiple_ts_long.drop(columns="index")

#%%
# keep only the first 10*24 timesteps for training but without greens.
multiple_ts_long_train = multiple_ts_long[
    ~multiple_ts_long["color"].isin(["green"])
    & (multiple_ts_long["date"] < pd.to_datetime("2021-01-10"))
]
# cast to category
multiple_ts_long_train["color"] = multiple_ts_long_train["color"].astype("category")

# keep only the last 5*24 timesteps for testing but only greens.
greens = multiple_ts_long[
    multiple_ts_long["color"].isin(["green"])
    & (multiple_ts_long["date"] >= pd.to_datetime("2021-01-10"))
]
# all the blues and reds with full history for testing
blue_red = multiple_ts_long[multiple_ts_long["color"].isin(["blue", "red"])]

# concatenate the two test sets.
multiple_ts_long_test = pd.concat([blue_red, greens])
multiple_ts_long_test["color"] = multiple_ts_long_test["color"].astype("category")

#%%
# for long-dataset we use a different constructor and need a `item_id` column
multiple_ts_long_dataset_train = PandasDataset.from_long_dataframe(
    multiple_ts_long_train.set_index("date"),
    item_id="item_id",
    feat_dynamic_real=["dynamic_real_1", "dynamic_real_2"],
    static_feature_columns=["color"],
)
multiple_ts_long_dataset_test = PandasDataset.from_long_dataframe(
    multiple_ts_long_test.set_index("date"),
    item_id="item_id",
    feat_dynamic_real=["dynamic_real_1", "dynamic_real_2"],
    static_feature_columns=["color"],
)
#%%
stats = calculate_dataset_statistics(multiple_ts_long_dataset_train)
#%%
estimator = TemporalFusionTransformerEstimator(
    freq=freq,
    prediction_length=prediction_length,
    static_cardinalities=[len(cats) for cats in stats.feat_static_cat],
    batch_size=5,
    dynamic_dims=[1, 1],
    trainer_kwargs={"max_epochs": 3, "deterministic": True},
)
#%%
predictor = estimator.train(training_data=multiple_ts_long_dataset_train)
#%%
fss, tss = make_evaluation_predictions(
    predictor=predictor, dataset=multiple_ts_long_dataset_test, num_samples=2000
)
#%%
preds_list = list(fss)
```

## Error message or code output

```
Traceback (most recent call last):
  File "/Users/guti1/.pyenv/versions/tft/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-75-e4c8290a6d4e>", line 1, in <module>
    preds_list = list(fss)
  File "/Users/guti1/.pyenv/versions/3.9.16/envs/tft/lib/python3.9/site-packages/gluonts/torch/model/predictor.py", line 85, in predict
    yield from self.forecast_generator(
  File "/Users/guti1/.pyenv/versions/3.9.16/envs/tft/lib/python3.9/site-packages/gluonts/model/forecast_generator.py", line 119, in __call__
    outputs = predict_to_numpy(prediction_net, inputs)
  File "/Users/guti1/.pyenv/versions/3.9.16/lib/python3.9/functools.py", line 888, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/guti1/.pyenv/versions/3.9.16/envs/tft/lib/python3.9/site-packages/gluonts/torch/model/predictor.py", line 38, in _
    return prediction_net(*args).cpu().numpy()
  File "/Users/guti1/.pyenv/versions/3.9.16/envs/tft/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/guti1/.pyenv/versions/3.9.16/envs/tft/lib/python3.9/site-packages/gluonts/torch/model/tft/lightning_module.py", line 66, in forward
    return self.model(*args, **kwargs)
  File "/Users/guti1/.pyenv/versions/3.9.16/envs/tft/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/guti1/.pyenv/versions/3.9.16/envs/tft/lib/python3.9/site-packages/gluonts/torch/model/tft/module.py", line 312, in forward
    ) = self._preprocess(
  File "/Users/guti1/.pyenv/versions/3.9.16/envs/tft/lib/python3.9/site-packages/gluonts/torch/model/tft/module.py", line 284, in _preprocess
    embs = self.feat_static_embed(feat_static_cat)
  File "/Users/guti1/.pyenv/versions/3.9.16/envs/tft/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/guti1/.pyenv/versions/3.9.16/envs/tft/lib/python3.9/site-packages/gluonts/torch/model/tft/layers.py", line 26, in forward
    concat_features = super().forward(features=features)
  File "/Users/guti1/.pyenv/versions/3.9.16/envs/tft/lib/python3.9/site-packages/gluonts/torch/modules/feature.py", line 44, in forward
    [
  File "/Users/guti1/.pyenv/versions/3.9.16/envs/tft/lib/python3.9/site-packages/gluonts/torch/modules/feature.py", line 45, in <listcomp>
    embed(cat_feature_slice.squeeze(-1))
  File "/Users/guti1/.pyenv/versions/3.9.16/envs/tft/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/guti1/.pyenv/versions/3.9.16/envs/tft/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/Users/guti1/.pyenv/versions/3.9.16/envs/tft/lib/python3.9/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

```

## Environment
- Operating system: MacOS
- Python version: 3.9.16
- GluonTS version: 0.12.7
- MXNet version: 1.9.1
- Torch version: 2.0.0

**Comment by shchur** [comment]
Have you checked if other models like DeepAR (PyTorch version) handle this differently? This looks like expected behavior to me.

If we include the extra categories when creating the model, but these categories are not present in the training set, the model won't learn meaningful embeddings for them. 

My recommendation would be to implement a preprocessing step outside the model, where all categories not present in the training set are replaced by some dummy value (e.g., by the most frequent category in the training set).

**Comment by guti1** [comment]
Hi,

thanks for looking into it! Yes, the DeepAR with the pytorch backend behaves the same way, the MXnet version however does not have a problem with that scenario.

**Comment by shchur** [comment]
To me this looks like something that should be handled outside the models, as this is default behavior of `torch.nn.Embedding` and the user should themselves decide what strategy is appropriate for their use case (extra token for missing values, imputing mode, etc). Not sure how the MXNet models deal with it. @lostella, what is your take on this?

**Comment by lostella** [comment]
I think the embedding silently handling new categorical values is a bug hidden waiting to be found, the way torch handles it makes much more sense to me. So probably yes, this is expected behaviour.

**Comment by guti1** [comment]
That sounds all reasonable, thanks for checking, I think we could close the issue then.
