### ISSUE TITLE
Models improperly handling additional (unused) data attributes

### ISSUE THREAD

**Issue by lostella** [awslabs/gluon-ts#2904]
## Description
Unused data attributes (such as `past_feat_dynamic_real`) are not ignored by data loading, and break the predictor due to shape issues: the `past_feat_dynamic_real` field from a batch of entries is not being properly sliced, but still it's being stacked together, breaking inference when entries have different lengths.

## To Reproduce

```python
from gluonts.torch.model.deepar import DeepAREstimator

import pandas as pd
import numpy as np

estimator = DeepAREstimator(
    freq="1H",
    prediction_length=10,
    context_length=10,
    num_feat_dynamic_real=1,
    trainer_kwargs=dict(max_epochs=1),
)

data_train = [
    {
        "start": pd.Period("2020-01-01", freq="1H"),
        "target": np.ones(shape=(500,)),
        "feat_dynamic_real": np.ones(shape=(1, 500)),
        "past_feat_dynamic_real": np.ones(shape=(1, 500)),
    },
    {
        "start": pd.Period("2020-01-01", freq="1H"),
        "target": np.ones(shape=(300,)),
        "feat_dynamic_real": np.ones(shape=(1, 300)),
        "past_feat_dynamic_real": np.ones(shape=(1, 300)),
    }
]

predictor = estimator.train(data_train)

data_pred = [
    {
        "start": pd.Period("2020-01-01", freq="1H"),
        "target": np.ones(shape=(500,)),
        "feat_dynamic_real": np.ones(shape=(1, 510)),
        "past_feat_dynamic_real": np.ones(shape=(1, 500)),
    },
    {
        "start": pd.Period("2020-01-01", freq="1H"),
        "target": np.ones(shape=(300,)),
        "feat_dynamic_real": np.ones(shape=(1, 310)),
        "past_feat_dynamic_real": np.ones(shape=(1, 300)),
    }
]

forecasts = list(predictor.predict(data_pred))
```

## Error message or code output

```
Traceback (most recent call last):
  File "reproduce.py", line 68, in <module>
    forecasts = list(predictor.predict(data_pred))
  File "/Users/stellalo/gluonts/src/gluonts/torch/model/predictor.py", line 85, in predict
    yield from self.forecast_generator(
  File "/Users/stellalo/gluonts/src/gluonts/model/forecast_generator.py", line 154, in __call__
    for batch in inference_data_loader:
  File "/Users/stellalo/gluonts/src/gluonts/transform/_base.py", line 111, in __iter__
    yield from self.transformation(
  File "/Users/stellalo/gluonts/src/gluonts/transform/_base.py", line 136, in __call__
    raise e
  File "/Users/stellalo/gluonts/src/gluonts/transform/_base.py", line 134, in __call__
    yield self.map_transform(data_entry.copy(), is_train)
  File "/Users/stellalo/gluonts/src/gluonts/transform/_base.py", line 149, in map_transform
    return self.transform(data)
  File "/Users/stellalo/gluonts/src/gluonts/transform/_base.py", line 169, in transform
    return self.func(data.copy())
  File "/Users/stellalo/gluonts/src/gluonts/torch/model/predictor.py", line 79, in <lambda>
    stack_fn=lambda data: batchify(data, self.device),
  File "/Users/stellalo/gluonts/src/gluonts/torch/batchify.py", line 33, in batchify
    return {
  File "/Users/stellalo/gluonts/src/gluonts/torch/batchify.py", line 34, in <dictcomp>
    key: stack(data=[item[key] for item in data], device=device)
  File "/Users/stellalo/gluonts/src/gluonts/torch/batchify.py", line 24, in stack
    data = torch.tensor(np.array(data), device=device)
ValueError: could not broadcast input array from shape (500,) into shape (1,)
```

## Environment
- Operating system:
- Python version:
- GluonTS version: `dev`
- MXNet version:

**Comment by lostella** [comment]
Update: replacing the estimator with the mxnet based one gives a similar issue

```python
from gluonts.mx.model.deepar import DeepAREstimator
from gluonts.mx.trainer import Trainer

estimator = DeepAREstimator(
    freq="1H",
    prediction_length=10,
    context_length=10,
    trainer=Trainer(epochs=1),
)

[...]
```

```
Traceback (most recent call last):
  File "reproduce.py", line 56, in <module>
    forecasts = list(predictor.predict(data_pred))
  File "/Users/stellalo/gluonts/src/gluonts/mx/model/predictor.py", line 163, in predict
    yield from self.forecast_generator(
  File "/Users/stellalo/gluonts/src/gluonts/model/forecast_generator.py", line 154, in __call__
    for batch in inference_data_loader:
  File "/Users/stellalo/gluonts/src/gluonts/transform/_base.py", line 111, in __iter__
    yield from self.transformation(
  File "/Users/stellalo/gluonts/src/gluonts/transform/_base.py", line 136, in __call__
    raise e
  File "/Users/stellalo/gluonts/src/gluonts/transform/_base.py", line 134, in __call__
    yield self.map_transform(data_entry.copy(), is_train)
  File "/Users/stellalo/gluonts/src/gluonts/transform/_base.py", line 149, in map_transform
    return self.transform(data)
  File "/Users/stellalo/gluonts/src/gluonts/transform/_base.py", line 169, in transform
    return self.func(data.copy())
  File "/Users/stellalo/gluonts/src/gluonts/mx/batchify.py", line 103, in batchify
    return {
  File "/Users/stellalo/gluonts/src/gluonts/mx/batchify.py", line 104, in <dictcomp>
    key: stack(
  File "/Users/stellalo/gluonts/src/gluonts/mx/batchify.py", line 81, in stack
    data = mx.nd.array(data, dtype=dtype, ctx=ctx)
  File "/Users/stellalo/.pyenv/versions/gluonts/lib/python3.8/site-packages/mxnet/ndarray/utils.py", line 146, in array
    return _array(source_array, ctx=ctx, dtype=dtype)
  File "/Users/stellalo/.pyenv/versions/gluonts/lib/python3.8/site-packages/mxnet/ndarray/ndarray.py", line 3366, in array
    raise TypeError('source_array must be array like object')
TypeError: source_array must be array like object
```

**Comment by lostella** [comment]
It’s also questionable what the desired behaviour in these cases would be: failing like this is not so nice, when just ignoring any additional data field would suffice; on the other hand, silently ignoring parts of the data is not transparent, the user may think that those fields are actually being used when they're not.
