### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed>

### ISSUE THREAD

**Issue by sunnyccshine** [awslabs/gluon-ts#3039]
## Description
I ran the tutorial code from the official website, but I encountered the following error during the data import session

## To Reproduce
```python
from gluonts.dataset.repository import get_dataset, dataset_names
from gluonts.dataset.util import to_pandas
print(f"Available datasets: {dataset_names}")
dataset = get_dataset("m4_hourly")
print(dataset.train)
print(dataset.test)
print(dataset.metadata)
```

## Error message or code output
```
Traceback (most recent call last):
  File "D:\anaconda\envs\GluonTS\lib\urllib\request.py", line 1317, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\anaconda\envs\GluonTS\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\anaconda\envs\GluonTS\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\anaconda\envs\GluonTS\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\anaconda\envs\GluonTS\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "D:\anaconda\envs\GluonTS\lib\http\client.py", line 944, in send
    self.connect()
  File "D:\anaconda\envs\GluonTS\lib\http\client.py", line 1392, in connect
    super().connect()
  File "D:\anaconda\envs\GluonTS\lib\http\client.py", line 915, in connect
    self.sock = self._create_connection(
  File "D:\anaconda\envs\GluonTS\lib\socket.py", line 807, in create_connection
    raise err
  File "D:\anaconda\envs\GluonTS\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pythonProject\Forecast.py", line 6, in <module>
    dataset = get_dataset("m4_hourly")
  File "D:\anaconda\envs\GluonTS\lib\site-packages\gluonts\dataset\repository\datasets.py", line 360, in get_dataset
    dataset_path = materialize_dataset(
  File "D:\anaconda\envs\GluonTS\lib\site-packages\gluonts\dataset\repository\datasets.py", line 307, in materialize_dataset
    dataset_recipe(**kwargs)
  File "D:\anaconda\envs\GluonTS\lib\site-packages\gluonts\dataset\repository\_m4.py", line 34, in generate_m4_dataset
    train_df = pd.read_csv(
  File "D:\anaconda\envs\GluonTS\lib\site-packages\pandas\io\parsers\readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "D:\anaconda\envs\GluonTS\lib\site-packages\pandas\io\parsers\readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "D:\anaconda\envs\GluonTS\lib\site-packages\pandas\io\parsers\readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "D:\anaconda\envs\GluonTS\lib\site-packages\pandas\io\parsers\readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "D:\anaconda\envs\GluonTS\lib\site-packages\pandas\io\common.py", line 716, in get_handle
    ioargs = _get_filepath_or_buffer(
  File "D:\anaconda\envs\GluonTS\lib\site-packages\pandas\io\common.py", line 368, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
  File "D:\anaconda\envs\GluonTS\lib\site-packages\pandas\io\common.py", line 270, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "D:\anaconda\envs\GluonTS\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\anaconda\envs\GluonTS\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "D:\anaconda\envs\GluonTS\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\anaconda\envs\GluonTS\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "D:\anaconda\envs\GluonTS\lib\urllib\request.py", line 1360, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\anaconda\envs\GluonTS\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
```

## Environment
- Operating system: Windows
- Python version: 3.8.0
- GluonTS version: 0.14.0

**Comment by lostella** [comment]
@sunnyccshine I suspect this is not a bug. Does the following work, or raise a similar issue?

```python
import urllib
urllib.request.urlopen("https://www.google.com").read()
```

**Comment by sunnyccshine** [comment]
Thank you for your patient reply. When I try to access Google by Python, it also raises the same question. I guess I didn't configure the VPN correctly. I will search for a method to configure a VPN to access it.
