### ISSUE TITLE
GPU setup broken 

### ISSUE THREAD

**Issue by marvin-hansen** [awslabs/gluon-ts#374]
## Description

Installation of GPU enabled mxnet still runs gluonts code on CPU. 

## To Reproduce
$ pip install gluonts 
$ pip install mxnet-cu100==1.4.1 # Avoids the 1.5 bug and matches exact CUDA version

import mxnet as mx
print("Number GPU's: " + str(mx.context.num_gpus()))

Returns 0 

Essentially, installing mxnet with CUDA supports makes no difference. 
The same conda environment with PyTorch finds CUDA. 

uninstalling the non-cuda mx package causes an error, and installing it leads to not using the GPU.  

## Error Message

`
Traceback (most recent call last):
  File "C:/Users/marvi/PycharmProjects/GNL/Examples/bechmark_models.py", line 10, in <module>
    from gluonts.dataset.repository.datasets import get_dataset
  File "C:\Users\marvi\Anaconda3\envs\GNL\lib\site-packages\gluonts\dataset\repository\datasets.py", line 19, in <module>
    from gluonts.dataset.artificial import ConstantDataset
  File "C:\Users\marvi\Anaconda3\envs\GNL\lib\site-packages\gluonts\dataset\artificial\__init__.py", line 15, in <module>
    from ._base import (
  File "C:\Users\marvi\Anaconda3\envs\GNL\lib\site-packages\gluonts\dataset\artificial\_base.py", line 24, in <module>
    from gluonts.dataset.common import (
  File "C:\Users\marvi\Anaconda3\envs\GNL\lib\site-packages\gluonts\dataset\common.py", line 41, in <module>
    from gluonts.dataset.stat import (
  File "C:\Users\marvi\Anaconda3\envs\GNL\lib\site-packages\gluonts\dataset\stat.py", line 23, in <module>
    from gluonts.core.component import validated
  File "C:\Users\marvi\Anaconda3\envs\GNL\lib\site-packages\gluonts\core\component.py", line 26, in <module>
    import mxnet as mx
  File "C:\Users\marvi\Anaconda3\envs\GNL\lib\site-packages\mxnet\__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "C:\Users\marvi\Anaconda3\envs\GNL\lib\site-packages\mxnet\context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "C:\Users\marvi\Anaconda3\envs\GNL\lib\site-packages\mxnet\base.py", line 213, in <module>
    _LIB = _load_lib()
  File "C:\Users\marvi\Anaconda3\envs\GNL\lib\site-packages\mxnet\base.py", line 204, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "C:\Users\marvi\Anaconda3\envs\GNL\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
`

## Environment
- Operating system: Windows 10 
- Python version: 3.7 
- GluonTS version: 0.3 

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by strawberrypie** [comment]
I think that the problem is that GluonTS checks the presence of GPUs by calling `nvidia-smi` ([here](https://github.com/awslabs/gluon-ts/blob/master/setup.py#L21)), and this method doesn't work properly on Windows. Here is an article on `nvidia-smi` on Windows: https://stackoverflow.com/questions/57100015/how-do-i-run-nvidia-smi-on-windows

**Comment by marvin-hansen** [comment]
@strawberrypie nvidia-smi works fine and I can train PyTorch code on GPU. 

@jgasthaus yes, you are right, it is a mxnet issue. Suggestions or close this issue?

**Comment by marvin-hansen** [comment]
The MXNET GPU issue seems to be related to conda / cudatoolkit and indeed unrelated.
