### ISSUE TITLE
Invalid Frequency For Monthly Data

### ISSUE THREAD

**Issue by wizcheu** [awslabs/gluon-ts#525]
## Description
When I use monthly frequency data(freq=`MS`, which is a [valid time series frequency unit](https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases)), DeepAREstimator and GaussianProcessEstimator will throw Exception but SimpleFeedForwardEstimator can work well.

----
## To Reproduce
**For DeepAREstimator**
``` python
import numpy as np
import pandas as pd
from gluonts.dataset.common import ListDataset
from gluonts.model.deepar import DeepAREstimator
from gluonts.trainer import Trainer
from gluonts.evaluation.backtest import make_evaluation_predictions

N = 10  # number of time series
T = 100  # number of timesteps
prediction_length = 24
freq = "MS"
custom_dataset = np.random.normal(size=(N, T))
start = pd.Timestamp("01-01-2019", freq=freq)  # can be different for each time series
# train dataset: cut the last window of length "prediction_length", add "target" and "start" fields
train_ds = ListDataset([{'target': x, 'start': start}
                        for x in custom_dataset[:, :-prediction_length]],
                       freq=freq)
# test dataset: use the whole dataset, add "target" and "start" fields
test_ds = ListDataset([{'target': x, 'start': start}
                       for x in custom_dataset],
                      freq=freq)
estimator = DeepAREstimator(
    prediction_length=prediction_length,
    freq=freq,
    trainer=Trainer(ctx="cpu",
                    epochs=5,
                    learning_rate=1e-3,
                    num_batches_per_epoch=100)
)
predictor = estimator.train(train_ds)
forecast_it, ts_it = make_evaluation_predictions(
    dataset=test_ds,  # test dataset
    predictor=predictor,  # predictor
    num_samples=100,  # number of sample paths we want for evaluation
)
```

**For GaussianProcessEstimator**
``` python
import numpy as np
import pandas as pd
from gluonts.dataset.common import ListDataset
from gluonts.model.gp_forecaster import GaussianProcessEstimator
from gluonts.trainer import Trainer
from gluonts.evaluation.backtest import make_evaluation_predictions

N = 10  # number of time series
T = 100  # number of timesteps
prediction_length = 24
freq = "MS"
custom_dataset = np.random.normal(size=(N, T))
start = pd.Timestamp("01-01-2019", freq=freq)  # can be different for each time series
# train dataset: cut the last window of length "prediction_length", add "target" and "start" fields
train_ds = ListDataset([{'target': x, 'start': start}
                        for x in custom_dataset[:, :-prediction_length]],
                       freq=freq)
# test dataset: use the whole dataset, add "target" and "start" fields
test_ds = ListDataset([{'target': x, 'start': start}
                       for x in custom_dataset],
                      freq=freq)
estimator = GaussianProcessEstimator(
    cardinality=N,
    prediction_length=prediction_length,
    freq=freq,
    trainer=Trainer(ctx="cpu",
                    epochs=5,
                    learning_rate=1e-3,
                    num_batches_per_epoch=100)
)
predictor = estimator.train(train_ds)
forecast_it, ts_it = make_evaluation_predictions(
    dataset=test_ds,  # test dataset
    predictor=predictor,  # predictor
    num_samples=100,  # number of sample paths we want for evaluation
)
```

----
## Error Message
**For DeepAREstimator**
``` log
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/usr/local/lib/python3.6/dist-packages/gluonts/core/component.py", line 443, in init_wrapper
    return init(self, **all_args)
  File "/usr/local/lib/python3.6/dist-packages/gluonts/model/deepar/_estimator.py", line 188, in __init__
    else get_lags_for_frequency(freq_str=freq)
  File "/usr/local/lib/python3.6/dist-packages/gluonts/time_feature/lag.py", line 115, in get_lags_for_frequency
    raise Exception("invalid frequency")
Exception: invalid frequency
```

**For GaussianProcessEstimator**
``` log
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/gluonts/model/estimator.py", line 223, in train
    return self.train_model(training_data, validation_data).predictor
  File "/usr/local/lib/python3.6/dist-packages/gluonts/model/estimator.py", line 208, in train_model
    validation_iter=validation_data_loader,
  File "/usr/local/lib/python3.6/dist-packages/gluonts/trainer/_base.py", line 297, in __call__
    epoch_loss = loop(epoch_no, train_iter)
  File "/usr/local/lib/python3.6/dist-packages/gluonts/trainer/_base.py", line 230, in loop
    for batch_no, data_entry in enumerate(it, start=1):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 1060, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/gluonts/dataset/loader.py", line 192, in __iter__
    data_entry = next(self._cur_iter)
  File "/usr/local/lib/python3.6/dist-packages/gluonts/transform.py", line 324, in __call__
    for data_entry in data_it:
  File "/usr/local/lib/python3.6/dist-packages/gluonts/transform.py", line 275, in __call__
    for data_entry in data_it:
  File "/usr/local/lib/python3.6/dist-packages/gluonts/transform.py", line 275, in __call__
    for data_entry in data_it:
  File "/usr/local/lib/python3.6/dist-packages/gluonts/transform.py", line 279, in __call__
    raise e
  File "/usr/local/lib/python3.6/dist-packages/gluonts/transform.py", line 277, in __call__
    yield self.map_transform(data_entry.copy(), is_train)
  File "/usr/local/lib/python3.6/dist-packages/gluonts/transform.py", line 851, in map_transform
    self._update_cache(start, length)
  File "/usr/local/lib/python3.6/dist-packages/gluonts/transform.py", line 829, in _update_cache
    shift_timestamp(end, 50), self._max_time_point
  File "/usr/local/lib/python3.6/dist-packages/gluonts/transform.py", line 62, in shift_timestamp
    return _shift_timestamp_helper(ts, ts.freq, offset)
  File "/usr/local/lib/python3.6/dist-packages/gluonts/transform.py", line 83, in _shift_timestamp_helper
    return ts + offset * ts.freq
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
```

----
## Environment
- Operating system: Ubuntu 18.04 LTS
- Python version: Python 3.6.9
- GluonTS version: 0.4.2

**Comment by jaheba** [comment]
Hello,

We do not currently support all pandas frequencies. See #264

I would suggest to use M as the monthly frequency. Or, if you really need MS, we are happy to accept contributions.

**Comment by wizcheu** [comment]
The error still occurs when I change `freq = "MS"` to `freq = "M"`.

**Comment by jaheba** [comment]
Both your examples work for me, using `gluonts==0.4.2`. In fact, the gaussian one does also work with `MS` for me.

**Comment by jaheba** [comment]
@wizcheu what pandas version are you using? I remember us having issue with an older version.

**Comment by wizcheu** [comment]
@jaheba `pandas==0.23.4`. When I update the pandas to `0.25.3`, it works! Thanks for your reply~
