### ISSUE TITLE
simple_feedforward throws an exception at import

### ISSUE THREAD

**Issue by rherbrich74** [awslabs/gluon-ts#67]
I was just going through the tutorial given at https://gluon-ts.mxnet.io/examples/forecasting/tutorial.html and encountered this problem at step #11 (I am working on macOS and Python 3.7). What shall I do?

----

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydantic/validators.py", line 262, in find_validators
    if issubclass(type_, val_type):
TypeError: issubclass() arg 1 must be a class

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 31, in <module>
    from gluonts.model.simple_feedforward import SimpleFeedForwardEstimator
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gluonts/model/simple_feedforward/__init__.py", line 2, in <module>
    from ._estimator import SimpleFeedForwardEstimator
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gluonts/model/simple_feedforward/_estimator.py", line 9, in <module>
    from gluonts.distribution import DistributionOutput, StudentTOutput
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gluonts/distribution/__init__.py", line 16, in <module>
    from .binned import Binned, BinnedOutput
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gluonts/distribution/binned.py", line 168, in <module>
    class BinnedOutput(DistributionOutput):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gluonts/distribution/binned.py", line 172, in BinnedOutput
    def __init__(self, bin_centers: List) -> None:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/gluonts/core/component.py", line 169, in validator
    **ctor_fields,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydantic/main.py", line 410, in create_model
    config=config,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydantic/fields.py", line 107, in infer
    schema=schema,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydantic/fields.py", line 87, in __init__
    self.prepare()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydantic/fields.py", line 136, in prepare
    self._populate_validators()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydantic/fields.py", line 266, in _populate_validators
    self.model_config.arbitrary_types_allowed)),
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydantic/validators.py", line 265, in find_validators
    raise RuntimeError(f'error checking inheritance of {type_!r} (type: {display_as_type(type_)})') from e
RuntimeError: error checking inheritance of ~T (type: T)

**Comment by rherbrich74** [comment]
Here is the full tutorial code; the problem happens at line 30

import mxnet as mx
from mxnet import gluon
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json

from gluonts.dataset.repository.datasets import get_dataset, dataset_recipes
from gluonts.dataset.util import to_pandas

print(f"Available datasets: {list(dataset_recipes.keys())}")

dataset = get_dataset("m4_hourly", regenerate=False)

entry = next(iter(dataset.train))
train_series = to_pandas(entry)
train_series.plot()
plt.grid(which="both")
plt.legend(["train series"], loc="upper left")
plt.show()

entry = next(iter(dataset.test))
test_series = to_pandas(entry)
test_series.plot()
plt.axvline(train_series.index[-1], color='r') # end of train dataset
plt.grid(which="both")
plt.legend(["test series", "end of train series"], loc="upper left")
plt.show()

from gluonts.model.simple_feedforward import SimpleFeedForwardEstimator

**Comment by jgasthaus** [comment]
Thanks for reporting this, @rherbrich74! 

This seems to be the same issue as #62. I think I have identified the problem (occurs only with some Python 3.7.x versions) and #68 should resolve it.

While we are preparing a new release, can you try upgrading to a development version that includes this fix, 

    pip install --upgrade git+https://github.com/jgasthaus/gluon-ts@fix_python37

**Comment by rherbrich74** [comment]
Thanks, @jgasthaus - you patch is fixing it for me! Looking forward to the new release and thanks for the prompt response!
