### ISSUE TITLE
Extra unused parameter causing conflict

### ISSUE THREAD

**Issue by kaleming** [awslabs/gluon-ts#836]
## Description
Hi, 

I usually organize my json file as following:

{"_id": {"a": 1, "b": 1}, "start": "2011-01-29", "feat_static_cat": [0, 0, 0, 0], "feat_dynamic_real": [[30, 30, 30, 30, 30, 30 ..], [4, 4, 4, 4, 4, 4, 4, ...], [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4....], [2, 2, 2, 2, 2, 2, 2, 2, 2, 2...], [0, 0, 0, 1, 1, 1...], [2.240234375, 2.240234375, 2.240234375, 2.240234375 ...]], "target": [5, 5, 1, 1, 0, 3, 3, 4, 9, 4, 7, 1, 2, 4, 14 ...]}`

And everything always worked fine. However, for the first time, this extra (unused) "_id" parameter seems to cause some trouble. 

## Error message or code output

Using Deepar estimator:

```python
1328it [04:12,  5.26it/s, epoch=16/60, validation_avg_epoch_loss=1.44]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:19<00:00,  3.29it/s, epoch=17/60, avg_epoch_loss=1.64]
1344it [04:19,  5.19it/s, epoch=17/60, validation_avg_epoch_loss=1.45]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:19<00:00,  3.20it/s, epoch=18/60, avg_epoch_loss=1.89]
1351it [04:11,  5.38it/s, epoch=18/60, validation_avg_epoch_loss=1.44]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:16<00:00,  3.92it/s, epoch=19/60, avg_epoch_loss=2.55]
1344it [03:34,  6.28it/s, epoch=19/60, validation_avg_epoch_loss=1.45]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 64/64 [00:17<00:00,  3.64it/s, epoch=20/60, avg_epoch_loss=2.7]
1346it [03:53,  5.76it/s, epoch=20/60, validation_avg_epoch_loss=1.44]
  8%|██████████▊                                                                                                                                | 5/64 [00:02<00:25,  2.31it/s, epoch=21/60, avg_epoch_loss=3.28]
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    m = estimator.train(training_data=train_data, validation_data=validation_data)
  File "/home/leming/Documents/m_robot/venv_dir/lib/python3.7/site-packages/gluonts/model/estimator.py", line 252, in train
    training_data, validation_data, num_workers, num_prefetch, **kwargs
  File "/home/leming/Documents/m_robot/venv_dir/lib/python3.7/site-packages/gluonts/model/estimator.py", line 231, in train_model
    validation_iter=validation_data_loader,
  File "/home/leming/Documents/m_robot/venv_dir/lib/python3.7/site-packages/gluonts/trainer/_base.py", line 303, in __call__
    epoch_loss = loop(epoch_no, train_iter)
  File "/home/leming/Documents/m_robot/venv_dir/lib/python3.7/site-packages/gluonts/trainer/_base.py", line 231, in loop
    for batch_no, data_entry in enumerate(it, start=1):
  File "/home/leming/Documents/m_robot/venv_dir/lib/python3.7/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/home/leming/Documents/m_robot/venv_dir/lib/python3.7/site-packages/gluonts/dataset/loader.py", line 181, in __iter__
    for batch in self._it:
  File "/home/leming/Documents/m_robot/venv_dir/lib/python3.7/site-packages/gluonts/dataset/parallelized_loader.py", line 647, in same_process_iter
    single_process_ctx=self.ctx,
  File "/home/leming/Documents/m_robot/venv_dir/lib/python3.7/site-packages/gluonts/dataset/parallelized_loader.py", line 213, in batchify
    for key in data[0].keys()
  File "/home/leming/Documents/m_robot/venv_dir/lib/python3.7/site-packages/gluonts/dataset/parallelized_loader.py", line 213, in <dictcomp>
    for key in data[0].keys()
  File "/home/leming/Documents/m_robot/venv_dir/lib/python3.7/site-packages/gluonts/dataset/parallelized_loader.py", line 207, in <listcomp>
    data=[item[key] for item in data],
KeyError: '_id'
```

## Environment
- Operating system:Ubuntu
- Python version:3.7
- GluonTS version:0.5

I will try to remove this "_id" from the json file.

**Comment by lostella** [comment]
@kaleming is that field only present in some (but not all) the elements of your dataset? Because training seems to go on fine for a while, from what I see

**Comment by kaleming** [comment]
Yes, it is present in 20% of the dataset.

**Comment by kaleming** [comment]
I just deleted, and it's ok now.
