### ISSUE TITLE
Getting Nans when training MQCNN on GPU

### ISSUE THREAD

**Issue by AaronSpieler** [awslabs/gluon-ts#950]
## Description
```
FROM nvidia/cuda:9.2-cudnn7-runtime-ubuntu18.04

RUN apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends \
        wget bzip2 ca-certificates curl git build-essential \
        cmake python3.7 python3.7-dev python3.7-distutils pkg-config && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3.7 get-pip.py

# We're emulating nvidia-smi to be able to build GPU container on devices without GPU
RUN echo '#!/bin/bash\necho Building container with GPU support' > /usr/bin/nvidia-smi && \
    chmod +x /usr/bin/nvidia-smi

ADD . /gluonts

RUN pip3.7 install mxnet-cu92>=1.6
RUN pip3.7 install /gluonts[shell]

ENTRYPOINT ["python3.7", "-m", "gluonts.shell"]

```

- If I set `hybridize=False` it works again.
- This does not happen in our internal MXNet version/container (see MQCNN).
- This does not happen with older MXNet versions (I think 1.4)
- This does happen also for newer Cuda versions (I think 10.?)
- Reducing the initial learning rate only works for ridiculously low learning rates, and even then it's not reliable

## Error message or code output
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/gluonts/shell/__main__.py", line 154, in <module>
    cli(prog_name=__package__)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/gluonts/shell/__main__.py", line 131, in train_command
    train.run_train_and_test(env, forecaster_type_by_name(forecaster))
  File "/usr/local/lib/python3.7/dist-packages/gluonts/shell/train.py", line 85, in run_train_and_test
    forecaster, env.datasets["train"], env.datasets.get("validation")
  File "/usr/local/lib/python3.7/dist-packages/gluonts/shell/train.py", line 100, in run_train
    training_data=train_dataset, validation_data=validation_dataset
  File "/usr/local/lib/python3.7/dist-packages/gluonts/model/estimator.py", line 271, in train
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/gluonts/model/estimator.py", line 244, in train_model
    validation_iter=validation_data_loader,
  File "/usr/local/lib/python3.7/dist-packages/gluonts/mx/trainer/_base.py", line 373, in __call__
    "Got NaN in first epoch. Try reducing initial learning rate."
```

## Environment
- see Dockerfile

(Add as much information about your environment as possible, e.g. dependencies versions.)

**Comment by AaronSpieler** [comment]
Possibly related to: https://github.com/awslabs/gluon-ts/issues/501

**Comment by jwmueller** [comment]
Also facing similar issue as can be seen in the output logs here:  
http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1198/43/tutorials/forecasting/forecasting-quickstart.html  

where during GPU-training of MQCNN we see warnings like this: 
`Batch [8] of Epoch[0] gave NaN loss and it will be ignored`

This only seems to an issue for MQCNN with GPU on certain datasets (same code works fine running on CPU), eg. in the linked example we are running on a dataset that contains many 0s.

**Comment by lostella** [comment]
@jwmueller is there a way to isolate the issue into a MWE? That would be very useful to try to understand what is failing. I guess that requires extracting some data pre-processing from the `ForecastingPredictor` class of AutoGluon, and getting a sample HP settings that produces the issue (maybe default settings fail already?)

Work-around in the mean time: try disabling hybridization with MQCNN on GPU (does that slow down training by a lot?)
